// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/upload"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// PublicURL provides a mock function for the type MockManager
func (_mock *MockManager) PublicURL(objectKey string) string {
	ret := _mock.Called(objectKey)

	if len(ret) == 0 {
		panic("no return value specified for PublicURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(objectKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockManager_PublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicURL'
type MockManager_PublicURL_Call struct {
	*mock.Call
}

// PublicURL is a helper method to define mock.On call
//   - objectKey string
func (_e *MockManager_Expecter) PublicURL(objectKey interface{}) *MockManager_PublicURL_Call {
	return &MockManager_PublicURL_Call{Call: _e.mock.On("PublicURL", objectKey)}
}

func (_c *MockManager_PublicURL_Call) Run(run func(objectKey string)) *MockManager_PublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_PublicURL_Call) Return(s string) *MockManager_PublicURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockManager_PublicURL_Call) RunAndReturn(run func(objectKey string) string) *MockManager_PublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockManager
func (_mock *MockManager) Save(ctx context.Context, req upload.SaveUploadRequest, policy upload.Policy) (*upload.ContentResponse, error) {
	ret := _mock.Called(ctx, req, policy)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *upload.ContentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, upload.SaveUploadRequest, upload.Policy) (*upload.ContentResponse, error)); ok {
		return returnFunc(ctx, req, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, upload.SaveUploadRequest, upload.Policy) *upload.ContentResponse); ok {
		r0 = returnFunc(ctx, req, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*upload.ContentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, upload.SaveUploadRequest, upload.Policy) error); ok {
		r1 = returnFunc(ctx, req, policy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockManager_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - req upload.SaveUploadRequest
//   - policy upload.Policy
func (_e *MockManager_Expecter) Save(ctx interface{}, req interface{}, policy interface{}) *MockManager_Save_Call {
	return &MockManager_Save_Call{Call: _e.mock.On("Save", ctx, req, policy)}
}

func (_c *MockManager_Save_Call) Run(run func(ctx context.Context, req upload.SaveUploadRequest, policy upload.Policy)) *MockManager_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 upload.SaveUploadRequest
		if args[1] != nil {
			arg1 = args[1].(upload.SaveUploadRequest)
		}
		var arg2 upload.Policy
		if args[2] != nil {
			arg2 = args[2].(upload.Policy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_Save_Call) Return(contentResponse *upload.ContentResponse, err error) *MockManager_Save_Call {
	_c.Call.Return(contentResponse, err)
	return _c
}

func (_c *MockManager_Save_Call) RunAndReturn(run func(ctx context.Context, req upload.SaveUploadRequest, policy upload.Policy) (*upload.ContentResponse, error)) *MockManager_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SignURL provides a mock function for the type MockManager
func (_mock *MockManager) SignURL(ctx context.Context, req upload.SignURLRequest, policy upload.Policy) (*upload.SignURLResponse, error) {
	ret := _mock.Called(ctx, req, policy)

	if len(ret) == 0 {
		panic("no return value specified for SignURL")
	}

	var r0 *upload.SignURLResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, upload.SignURLRequest, upload.Policy) (*upload.SignURLResponse, error)); ok {
		return returnFunc(ctx, req, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, upload.SignURLRequest, upload.Policy) *upload.SignURLResponse); ok {
		r0 = returnFunc(ctx, req, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*upload.SignURLResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, upload.SignURLRequest, upload.Policy) error); ok {
		r1 = returnFunc(ctx, req, policy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_SignURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignURL'
type MockManager_SignURL_Call struct {
	*mock.Call
}

// SignURL is a helper method to define mock.On call
//   - ctx context.Context
//   - req upload.SignURLRequest
//   - policy upload.Policy
func (_e *MockManager_Expecter) SignURL(ctx interface{}, req interface{}, policy interface{}) *MockManager_SignURL_Call {
	return &MockManager_SignURL_Call{Call: _e.mock.On("SignURL", ctx, req, policy)}
}

func (_c *MockManager_SignURL_Call) Run(run func(ctx context.Context, req upload.SignURLRequest, policy upload.Policy)) *MockManager_SignURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 upload.SignURLRequest
		if args[1] != nil {
			arg1 = args[1].(upload.SignURLRequest)
		}
		var arg2 upload.Policy
		if args[2] != nil {
			arg2 = args[2].(upload.Policy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_SignURL_Call) Return(signURLResponse *upload.SignURLResponse, err error) *MockManager_SignURL_Call {
	_c.Call.Return(signURLResponse, err)
	return _c
}

func (_c *MockManager_SignURL_Call) RunAndReturn(run func(ctx context.Context, req upload.SignURLRequest, policy upload.Policy) (*upload.SignURLResponse, error)) *MockManager_SignURL_Call {
	_c.Call.Return(run)
	return _c
}
