// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"go-shop-backend/internal/upload"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPolicyRegistry creates a new instance of MockPolicyRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicyRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicyRegistry {
	mock := &MockPolicyRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPolicyRegistry is an autogenerated mock type for the PolicyRegistry type
type MockPolicyRegistry struct {
	mock.Mock
}

type MockPolicyRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPolicyRegistry) EXPECT() *MockPolicyRegistry_Expecter {
	return &MockPolicyRegistry_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockPolicyRegistry
func (_mock *MockPolicyRegistry) Get(t upload.Type) (upload.FilePolicy, error) {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 upload.FilePolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(upload.Type) (upload.FilePolicy, error)); ok {
		return returnFunc(t)
	}
	if returnFunc, ok := ret.Get(0).(func(upload.Type) upload.FilePolicy); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Get(0).(upload.FilePolicy)
	}
	if returnFunc, ok := ret.Get(1).(func(upload.Type) error); ok {
		r1 = returnFunc(t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPolicyRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - t upload.Type
func (_e *MockPolicyRegistry_Expecter) Get(t interface{}) *MockPolicyRegistry_Get_Call {
	return &MockPolicyRegistry_Get_Call{Call: _e.mock.On("Get", t)}
}

func (_c *MockPolicyRegistry_Get_Call) Run(run func(t upload.Type)) *MockPolicyRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 upload.Type
		if args[0] != nil {
			arg0 = args[0].(upload.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPolicyRegistry_Get_Call) Return(filePolicy upload.FilePolicy, err error) *MockPolicyRegistry_Get_Call {
	_c.Call.Return(filePolicy, err)
	return _c
}

func (_c *MockPolicyRegistry_Get_Call) RunAndReturn(run func(t upload.Type) (upload.FilePolicy, error)) *MockPolicyRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockPolicyRegistry
func (_mock *MockPolicyRegistry) Register(t upload.Type, filePolicy upload.FilePolicy) {
	_mock.Called(t, filePolicy)
	return
}

// MockPolicyRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockPolicyRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - t upload.Type
//   - filePolicy upload.FilePolicy
func (_e *MockPolicyRegistry_Expecter) Register(t interface{}, filePolicy interface{}) *MockPolicyRegistry_Register_Call {
	return &MockPolicyRegistry_Register_Call{Call: _e.mock.On("Register", t, filePolicy)}
}

func (_c *MockPolicyRegistry_Register_Call) Run(run func(t upload.Type, filePolicy upload.FilePolicy)) *MockPolicyRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 upload.Type
		if args[0] != nil {
			arg0 = args[0].(upload.Type)
		}
		var arg1 upload.FilePolicy
		if args[1] != nil {
			arg1 = args[1].(upload.FilePolicy)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyRegistry_Register_Call) Return() *MockPolicyRegistry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPolicyRegistry_Register_Call) RunAndReturn(run func(t upload.Type, filePolicy upload.FilePolicy)) *MockPolicyRegistry_Register_Call {
	_c.Run(run)
	return _c
}
