// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"go-shop-backend/internal/upload"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPolicyProvider creates a new instance of MockPolicyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicyProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicyProvider {
	mock := &MockPolicyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPolicyProvider is an autogenerated mock type for the PolicyProvider type
type MockPolicyProvider struct {
	mock.Mock
}

type MockPolicyProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPolicyProvider) EXPECT() *MockPolicyProvider_Expecter {
	return &MockPolicyProvider_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockPolicyProvider
func (_mock *MockPolicyProvider) Get(policy upload.Policy) (upload.FileConstraints, error) {
	ret := _mock.Called(policy)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 upload.FileConstraints
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(upload.Policy) (upload.FileConstraints, error)); ok {
		return returnFunc(policy)
	}
	if returnFunc, ok := ret.Get(0).(func(upload.Policy) upload.FileConstraints); ok {
		r0 = returnFunc(policy)
	} else {
		r0 = ret.Get(0).(upload.FileConstraints)
	}
	if returnFunc, ok := ret.Get(1).(func(upload.Policy) error); ok {
		r1 = returnFunc(policy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPolicyProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - policy upload.Policy
func (_e *MockPolicyProvider_Expecter) Get(policy interface{}) *MockPolicyProvider_Get_Call {
	return &MockPolicyProvider_Get_Call{Call: _e.mock.On("Get", policy)}
}

func (_c *MockPolicyProvider_Get_Call) Run(run func(policy upload.Policy)) *MockPolicyProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 upload.Policy
		if args[0] != nil {
			arg0 = args[0].(upload.Policy)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPolicyProvider_Get_Call) Return(fileConstraints upload.FileConstraints, err error) *MockPolicyProvider_Get_Call {
	_c.Call.Return(fileConstraints, err)
	return _c
}

func (_c *MockPolicyProvider_Get_Call) RunAndReturn(run func(policy upload.Policy) (upload.FileConstraints, error)) *MockPolicyProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockPolicyProvider
func (_mock *MockPolicyProvider) Register(policy upload.Policy, fc upload.FileConstraints) error {
	ret := _mock.Called(policy, fc)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(upload.Policy, upload.FileConstraints) error); ok {
		r0 = returnFunc(policy, fc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPolicyProvider_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockPolicyProvider_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - policy upload.Policy
//   - fc upload.FileConstraints
func (_e *MockPolicyProvider_Expecter) Register(policy interface{}, fc interface{}) *MockPolicyProvider_Register_Call {
	return &MockPolicyProvider_Register_Call{Call: _e.mock.On("Register", policy, fc)}
}

func (_c *MockPolicyProvider_Register_Call) Run(run func(policy upload.Policy, fc upload.FileConstraints)) *MockPolicyProvider_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 upload.Policy
		if args[0] != nil {
			arg0 = args[0].(upload.Policy)
		}
		var arg1 upload.FileConstraints
		if args[1] != nil {
			arg1 = args[1].(upload.FileConstraints)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPolicyProvider_Register_Call) Return(err error) *MockPolicyProvider_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPolicyProvider_Register_Call) RunAndReturn(run func(policy upload.Policy, fc upload.FileConstraints) error) *MockPolicyProvider_Register_Call {
	_c.Call.Return(run)
	return _c
}
