// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublicURLBuilder creates a new instance of MockPublicURLBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublicURLBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublicURLBuilder {
	mock := &MockPublicURLBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublicURLBuilder is an autogenerated mock type for the PublicURLBuilder type
type MockPublicURLBuilder struct {
	mock.Mock
}

type MockPublicURLBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublicURLBuilder) EXPECT() *MockPublicURLBuilder_Expecter {
	return &MockPublicURLBuilder_Expecter{mock: &_m.Mock}
}

// PublicURL provides a mock function for the type MockPublicURLBuilder
func (_mock *MockPublicURLBuilder) PublicURL(objectKey string) string {
	ret := _mock.Called(objectKey)

	if len(ret) == 0 {
		panic("no return value specified for PublicURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(objectKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPublicURLBuilder_PublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicURL'
type MockPublicURLBuilder_PublicURL_Call struct {
	*mock.Call
}

// PublicURL is a helper method to define mock.On call
//   - objectKey string
func (_e *MockPublicURLBuilder_Expecter) PublicURL(objectKey interface{}) *MockPublicURLBuilder_PublicURL_Call {
	return &MockPublicURLBuilder_PublicURL_Call{Call: _e.mock.On("PublicURL", objectKey)}
}

func (_c *MockPublicURLBuilder_PublicURL_Call) Run(run func(objectKey string)) *MockPublicURLBuilder_PublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublicURLBuilder_PublicURL_Call) Return(s string) *MockPublicURLBuilder_PublicURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPublicURLBuilder_PublicURL_Call) RunAndReturn(run func(objectKey string) string) *MockPublicURLBuilder_PublicURL_Call {
	_c.Call.Return(run)
	return _c
}
