// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEncryptionManager creates a new instance of MockEncryptionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncryptionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncryptionManager {
	mock := &MockEncryptionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEncryptionManager is an autogenerated mock type for the EncryptionManager type
type MockEncryptionManager struct {
	mock.Mock
}

type MockEncryptionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncryptionManager) EXPECT() *MockEncryptionManager_Expecter {
	return &MockEncryptionManager_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockEncryptionManager
func (_mock *MockEncryptionManager) Decrypt(ctx context.Context, encrypted string) (string, error) {
	ret := _mock.Called(ctx, encrypted)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, encrypted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, encrypted)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, encrypted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncryptionManager_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockEncryptionManager_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - encrypted string
func (_e *MockEncryptionManager_Expecter) Decrypt(ctx interface{}, encrypted interface{}) *MockEncryptionManager_Decrypt_Call {
	return &MockEncryptionManager_Decrypt_Call{Call: _e.mock.On("Decrypt", ctx, encrypted)}
}

func (_c *MockEncryptionManager_Decrypt_Call) Run(run func(ctx context.Context, encrypted string)) *MockEncryptionManager_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEncryptionManager_Decrypt_Call) Return(s string, err error) *MockEncryptionManager_Decrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEncryptionManager_Decrypt_Call) RunAndReturn(run func(ctx context.Context, encrypted string) (string, error)) *MockEncryptionManager_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockEncryptionManager
func (_mock *MockEncryptionManager) Encrypt(ctx context.Context, plaintext string) (string, error) {
	ret := _mock.Called(ctx, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, plaintext)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncryptionManager_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEncryptionManager_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - plaintext string
func (_e *MockEncryptionManager_Expecter) Encrypt(ctx interface{}, plaintext interface{}) *MockEncryptionManager_Encrypt_Call {
	return &MockEncryptionManager_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, plaintext)}
}

func (_c *MockEncryptionManager_Encrypt_Call) Run(run func(ctx context.Context, plaintext string)) *MockEncryptionManager_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEncryptionManager_Encrypt_Call) Return(s string, err error) *MockEncryptionManager_Encrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEncryptionManager_Encrypt_Call) RunAndReturn(run func(ctx context.Context, plaintext string) (string, error)) *MockEncryptionManager_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
