// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/pkg/paymentprovider"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// CancelPayment provides a mock function for the type MockProvider
func (_mock *MockProvider) CancelPayment(ctx context.Context, paymentID string, idempotencyKey string) error {
	ret := _mock.Called(ctx, paymentID, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for CancelPayment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, paymentID, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_CancelPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPayment'
type MockProvider_CancelPayment_Call struct {
	*mock.Call
}

// CancelPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
//   - idempotencyKey string
func (_e *MockProvider_Expecter) CancelPayment(ctx interface{}, paymentID interface{}, idempotencyKey interface{}) *MockProvider_CancelPayment_Call {
	return &MockProvider_CancelPayment_Call{Call: _e.mock.On("CancelPayment", ctx, paymentID, idempotencyKey)}
}

func (_c *MockProvider_CancelPayment_Call) Run(run func(ctx context.Context, paymentID string, idempotencyKey string)) *MockProvider_CancelPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_CancelPayment_Call) Return(err error) *MockProvider_CancelPayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_CancelPayment_Call) RunAndReturn(run func(ctx context.Context, paymentID string, idempotencyKey string) error) *MockProvider_CancelPayment_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePayment provides a mock function for the type MockProvider
func (_mock *MockProvider) CreatePayment(ctx context.Context, req *paymentprovider.CreatePaymentRequest, idempotencyKey string) (*paymentprovider.Payment, error) {
	ret := _mock.Called(ctx, req, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *paymentprovider.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *paymentprovider.CreatePaymentRequest, string) (*paymentprovider.Payment, error)); ok {
		return returnFunc(ctx, req, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *paymentprovider.CreatePaymentRequest, string) *paymentprovider.Payment); ok {
		r0 = returnFunc(ctx, req, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentprovider.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *paymentprovider.CreatePaymentRequest, string) error); ok {
		r1 = returnFunc(ctx, req, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockProvider_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - req *paymentprovider.CreatePaymentRequest
//   - idempotencyKey string
func (_e *MockProvider_Expecter) CreatePayment(ctx interface{}, req interface{}, idempotencyKey interface{}) *MockProvider_CreatePayment_Call {
	return &MockProvider_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, req, idempotencyKey)}
}

func (_c *MockProvider_CreatePayment_Call) Run(run func(ctx context.Context, req *paymentprovider.CreatePaymentRequest, idempotencyKey string)) *MockProvider_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *paymentprovider.CreatePaymentRequest
		if args[1] != nil {
			arg1 = args[1].(*paymentprovider.CreatePaymentRequest)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_CreatePayment_Call) Return(payment *paymentprovider.Payment, err error) *MockProvider_CreatePayment_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockProvider_CreatePayment_Call) RunAndReturn(run func(ctx context.Context, req *paymentprovider.CreatePaymentRequest, idempotencyKey string) (*paymentprovider.Payment, error)) *MockProvider_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockProvider
func (_mock *MockProvider) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockProvider_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockProvider_Expecter) GetName() *MockProvider_GetName_Call {
	return &MockProvider_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockProvider_GetName_Call) Run(run func()) *MockProvider_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_GetName_Call) Return(s string) *MockProvider_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_GetName_Call) RunAndReturn(run func() string) *MockProvider_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// ParseWebhook provides a mock function for the type MockProvider
func (_mock *MockProvider) ParseWebhook(body []byte) (*paymentprovider.WebhookEvent, error) {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for ParseWebhook")
	}

	var r0 *paymentprovider.WebhookEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*paymentprovider.WebhookEvent, error)); ok {
		return returnFunc(body)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *paymentprovider.WebhookEvent); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentprovider.WebhookEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_ParseWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseWebhook'
type MockProvider_ParseWebhook_Call struct {
	*mock.Call
}

// ParseWebhook is a helper method to define mock.On call
//   - body []byte
func (_e *MockProvider_Expecter) ParseWebhook(body interface{}) *MockProvider_ParseWebhook_Call {
	return &MockProvider_ParseWebhook_Call{Call: _e.mock.On("ParseWebhook", body)}
}

func (_c *MockProvider_ParseWebhook_Call) Run(run func(body []byte)) *MockProvider_ParseWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_ParseWebhook_Call) Return(webhookEvent *paymentprovider.WebhookEvent, err error) *MockProvider_ParseWebhook_Call {
	_c.Call.Return(webhookEvent, err)
	return _c
}

func (_c *MockProvider_ParseWebhook_Call) RunAndReturn(run func(body []byte) (*paymentprovider.WebhookEvent, error)) *MockProvider_ParseWebhook_Call {
	_c.Call.Return(run)
	return _c
}
