services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    volumes:
      - ./.env.docker:/app/.env:ro
    restart: always
    networks:
      - internal

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.docker
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - internal

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - nginx_cache:/var/cache/nginx
    depends_on:
      - app
      - minio
    restart: always
    networks:
      - internal

  redis:
    image: redis:8.6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: always
    networks:
      - internal

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - app
    restart: always
    networks:
      - internal

  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: asynq_monitor
    ports:
      - "3030:3030"
    command: [ "-redis-url=redis://:${REDIS_PASSWORD}@redis:6379/0", "-port=3030" ]
    depends_on:
      - redis
    restart: always
    networks:
      - internal

  loki:
    image: grafana/loki:latest
    container_name: loki
    env_file:
      - .env.docker
    ports:
      - "3100:3100"
    volumes:
      - ./deploy/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    command:
      - "-config.file=/etc/loki/loki-config.yaml"
      - "-config.expand-env=true"
    depends_on:
      minio:
        condition: service_healthy
    restart: always
    networks:
      - internal

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./deploy/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    depends_on:
      - loki
    restart: always
    networks:
      - internal

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./deploy/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - internal

volumes:
  postgres_data:
  redis_data:
  minio_data:
  nginx_cache:
  grafana_data:
  loki_data:
  prometheus_data:


networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24