// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAddressRepository creates a new instance of MockAddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddressRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddressRepository {
	mock := &MockAddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAddressRepository is an autogenerated mock type for the AddressRepository type
type MockAddressRepository struct {
	mock.Mock
}

type MockAddressRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddressRepository) EXPECT() *MockAddressRepository_Expecter {
	return &MockAddressRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAddressRepository
func (_mock *MockAddressRepository) Create(ctx context.Context, address *models.Address) error {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Address) error); ok {
		r0 = returnFunc(ctx, address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAddressRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAddressRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - address *models.Address
func (_e *MockAddressRepository_Expecter) Create(ctx interface{}, address interface{}) *MockAddressRepository_Create_Call {
	return &MockAddressRepository_Create_Call{Call: _e.mock.On("Create", ctx, address)}
}

func (_c *MockAddressRepository_Create_Call) Run(run func(ctx context.Context, address *models.Address)) *MockAddressRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Address
		if args[1] != nil {
			arg1 = args[1].(*models.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAddressRepository_Create_Call) Return(err error) *MockAddressRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAddressRepository_Create_Call) RunAndReturn(run func(ctx context.Context, address *models.Address) error) *MockAddressRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAddressRepository
func (_mock *MockAddressRepository) Delete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAddressRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAddressRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockAddressRepository_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}) *MockAddressRepository_Delete_Call {
	return &MockAddressRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *MockAddressRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockAddressRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAddressRepository_Delete_Call) Return(err error) *MockAddressRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAddressRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockAddressRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAddressRepository
func (_mock *MockAddressRepository) GetByID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*models.Address, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Address, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Address); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAddressRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAddressRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockAddressRepository_Expecter) GetByID(ctx interface{}, id interface{}, userID interface{}) *MockAddressRepository_GetByID_Call {
	return &MockAddressRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, userID)}
}

func (_c *MockAddressRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockAddressRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAddressRepository_GetByID_Call) Return(address *models.Address, err error) *MockAddressRepository_GetByID_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *MockAddressRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*models.Address, error)) *MockAddressRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockAddressRepository
func (_mock *MockAddressRepository) ListByUser(ctx context.Context, userID uuid.UUID) ([]*models.Address, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*models.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Address, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Address); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAddressRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockAddressRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAddressRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockAddressRepository_ListByUser_Call {
	return &MockAddressRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockAddressRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAddressRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAddressRepository_ListByUser_Call) Return(addresss []*models.Address, err error) *MockAddressRepository_ListByUser_Call {
	_c.Call.Return(addresss, err)
	return _c
}

func (_c *MockAddressRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*models.Address, error)) *MockAddressRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefault provides a mock function for the type MockAddressRepository
func (_mock *MockAddressRepository) SetDefault(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefault")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAddressRepository_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type MockAddressRepository_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockAddressRepository_Expecter) SetDefault(ctx interface{}, id interface{}, userID interface{}) *MockAddressRepository_SetDefault_Call {
	return &MockAddressRepository_SetDefault_Call{Call: _e.mock.On("SetDefault", ctx, id, userID)}
}

func (_c *MockAddressRepository_SetDefault_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockAddressRepository_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAddressRepository_SetDefault_Call) Return(err error) *MockAddressRepository_SetDefault_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAddressRepository_SetDefault_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockAddressRepository_SetDefault_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAddressRepository
func (_mock *MockAddressRepository) Update(ctx context.Context, address *models.Address) error {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Address) error); ok {
		r0 = returnFunc(ctx, address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAddressRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAddressRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - address *models.Address
func (_e *MockAddressRepository_Expecter) Update(ctx interface{}, address interface{}) *MockAddressRepository_Update_Call {
	return &MockAddressRepository_Update_Call{Call: _e.mock.On("Update", ctx, address)}
}

func (_c *MockAddressRepository_Update_Call) Run(run func(ctx context.Context, address *models.Address)) *MockAddressRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Address
		if args[1] != nil {
			arg1 = args[1].(*models.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAddressRepository_Update_Call) Return(err error) *MockAddressRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAddressRepository_Update_Call) RunAndReturn(run func(ctx context.Context, address *models.Address) error) *MockAddressRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
