// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/dto"
	"go-shop-backend/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// ListCategories provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) ListCategories(ctx context.Context, req dto.ListCategoryRequest) ([]*models.Category, int64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []*models.Category
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListCategoryRequest) ([]*models.Category, int64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListCategoryRequest) []*models.Category); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ListCategoryRequest) int64); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, dto.ListCategoryRequest) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCategoryRepository_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockCategoryRepository_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.ListCategoryRequest
func (_e *MockCategoryRepository_Expecter) ListCategories(ctx interface{}, req interface{}) *MockCategoryRepository_ListCategories_Call {
	return &MockCategoryRepository_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx, req)}
}

func (_c *MockCategoryRepository_ListCategories_Call) Run(run func(ctx context.Context, req dto.ListCategoryRequest)) *MockCategoryRepository_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ListCategoryRequest
		if args[1] != nil {
			arg1 = args[1].(dto.ListCategoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_ListCategories_Call) Return(categorys []*models.Category, n int64, err error) *MockCategoryRepository_ListCategories_Call {
	_c.Call.Return(categorys, n, err)
	return _c
}

func (_c *MockCategoryRepository_ListCategories_Call) RunAndReturn(run func(ctx context.Context, req dto.ListCategoryRequest) ([]*models.Category, int64, error)) *MockCategoryRepository_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}
