// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFavoriteRepository creates a new instance of MockFavoriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteRepository {
	mock := &MockFavoriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFavoriteRepository is an autogenerated mock type for the FavoriteRepository type
type MockFavoriteRepository struct {
	mock.Mock
}

type MockFavoriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteRepository) EXPECT() *MockFavoriteRepository_Expecter {
	return &MockFavoriteRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockFavoriteRepository
func (_mock *MockFavoriteRepository) Add(ctx context.Context, favorite *models.Favorite) error {
	ret := _mock.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Favorite) error); ok {
		r0 = returnFunc(ctx, favorite)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFavoriteRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockFavoriteRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - favorite *models.Favorite
func (_e *MockFavoriteRepository_Expecter) Add(ctx interface{}, favorite interface{}) *MockFavoriteRepository_Add_Call {
	return &MockFavoriteRepository_Add_Call{Call: _e.mock.On("Add", ctx, favorite)}
}

func (_c *MockFavoriteRepository_Add_Call) Run(run func(ctx context.Context, favorite *models.Favorite)) *MockFavoriteRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Favorite
		if args[1] != nil {
			arg1 = args[1].(*models.Favorite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavoriteRepository_Add_Call) Return(err error) *MockFavoriteRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFavoriteRepository_Add_Call) RunAndReturn(run func(ctx context.Context, favorite *models.Favorite) error) *MockFavoriteRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockFavoriteRepository
func (_mock *MockFavoriteRepository) Exists(ctx context.Context, productID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, productID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, productID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, productID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavoriteRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockFavoriteRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - userID uuid.UUID
func (_e *MockFavoriteRepository_Expecter) Exists(ctx interface{}, productID interface{}, userID interface{}) *MockFavoriteRepository_Exists_Call {
	return &MockFavoriteRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, productID, userID)}
}

func (_c *MockFavoriteRepository_Exists_Call) Run(run func(ctx context.Context, productID uuid.UUID, userID uuid.UUID)) *MockFavoriteRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavoriteRepository_Exists_Call) Return(b bool, err error) *MockFavoriteRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFavoriteRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID, userID uuid.UUID) (bool, error)) *MockFavoriteRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetListByUser provides a mock function for the type MockFavoriteRepository
func (_mock *MockFavoriteRepository) GetListByUser(ctx context.Context, userID uuid.UUID) ([]*models.FavoriteProductProjection, int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetListByUser")
	}

	var r0 []*models.FavoriteProductProjection
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.FavoriteProductProjection, int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.FavoriteProductProjection); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FavoriteProductProjection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) int64); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFavoriteRepository_GetListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListByUser'
type MockFavoriteRepository_GetListByUser_Call struct {
	*mock.Call
}

// GetListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockFavoriteRepository_Expecter) GetListByUser(ctx interface{}, userID interface{}) *MockFavoriteRepository_GetListByUser_Call {
	return &MockFavoriteRepository_GetListByUser_Call{Call: _e.mock.On("GetListByUser", ctx, userID)}
}

func (_c *MockFavoriteRepository_GetListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockFavoriteRepository_GetListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavoriteRepository_GetListByUser_Call) Return(favoriteProductProjections []*models.FavoriteProductProjection, n int64, err error) *MockFavoriteRepository_GetListByUser_Call {
	_c.Call.Return(favoriteProductProjections, n, err)
	return _c
}

func (_c *MockFavoriteRepository_GetListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*models.FavoriteProductProjection, int64, error)) *MockFavoriteRepository_GetListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockFavoriteRepository
func (_mock *MockFavoriteRepository) Remove(ctx context.Context, productID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, productID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, productID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFavoriteRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockFavoriteRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - userID uuid.UUID
func (_e *MockFavoriteRepository_Expecter) Remove(ctx interface{}, productID interface{}, userID interface{}) *MockFavoriteRepository_Remove_Call {
	return &MockFavoriteRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, productID, userID)}
}

func (_c *MockFavoriteRepository_Remove_Call) Run(run func(ctx context.Context, productID uuid.UUID, userID uuid.UUID)) *MockFavoriteRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavoriteRepository_Remove_Call) Return(err error) *MockFavoriteRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFavoriteRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID, userID uuid.UUID) error) *MockFavoriteRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}
