// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderItemRepository creates a new instance of MockOrderItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderItemRepository {
	mock := &MockOrderItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderItemRepository is an autogenerated mock type for the OrderItemRepository type
type MockOrderItemRepository struct {
	mock.Mock
}

type MockOrderItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderItemRepository) EXPECT() *MockOrderItemRepository_Expecter {
	return &MockOrderItemRepository_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function for the type MockOrderItemRepository
func (_mock *MockOrderItemRepository) AddItem(ctx context.Context, orderItem *models.OrderItem) error {
	ret := _mock.Called(ctx, orderItem)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.OrderItem) error); ok {
		r0 = returnFunc(ctx, orderItem)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderItemRepository_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockOrderItemRepository_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - orderItem *models.OrderItem
func (_e *MockOrderItemRepository_Expecter) AddItem(ctx interface{}, orderItem interface{}) *MockOrderItemRepository_AddItem_Call {
	return &MockOrderItemRepository_AddItem_Call{Call: _e.mock.On("AddItem", ctx, orderItem)}
}

func (_c *MockOrderItemRepository_AddItem_Call) Run(run func(ctx context.Context, orderItem *models.OrderItem)) *MockOrderItemRepository_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.OrderItem
		if args[1] != nil {
			arg1 = args[1].(*models.OrderItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderItemRepository_AddItem_Call) Return(err error) *MockOrderItemRepository_AddItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderItemRepository_AddItem_Call) RunAndReturn(run func(ctx context.Context, orderItem *models.OrderItem) error) *MockOrderItemRepository_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function for the type MockOrderItemRepository
func (_mock *MockOrderItemRepository) Clear(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderItemRepository_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockOrderItemRepository_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderItemRepository_Expecter) Clear(ctx interface{}, orderID interface{}) *MockOrderItemRepository_Clear_Call {
	return &MockOrderItemRepository_Clear_Call{Call: _e.mock.On("Clear", ctx, orderID)}
}

func (_c *MockOrderItemRepository_Clear_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderItemRepository_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderItemRepository_Clear_Call) Return(err error) *MockOrderItemRepository_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderItemRepository_Clear_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderItemRepository_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockOrderItemRepository
func (_mock *MockOrderItemRepository) DeleteItem(ctx context.Context, orderID uuid.UUID, productID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID, productID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderItemRepository_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockOrderItemRepository_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - productID uuid.UUID
func (_e *MockOrderItemRepository_Expecter) DeleteItem(ctx interface{}, orderID interface{}, productID interface{}) *MockOrderItemRepository_DeleteItem_Call {
	return &MockOrderItemRepository_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, orderID, productID)}
}

func (_c *MockOrderItemRepository_DeleteItem_Call) Run(run func(ctx context.Context, orderID uuid.UUID, productID uuid.UUID)) *MockOrderItemRepository_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderItemRepository_DeleteItem_Call) Return(err error) *MockOrderItemRepository_DeleteItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderItemRepository_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, productID uuid.UUID) error) *MockOrderItemRepository_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type MockOrderItemRepository
func (_mock *MockOrderItemRepository) GetItem(ctx context.Context, productID uuid.UUID, orderID uuid.UUID) (*models.OrderItem, error) {
	ret := _mock.Called(ctx, productID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *models.OrderItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.OrderItem, error)); ok {
		return returnFunc(ctx, productID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.OrderItem); ok {
		r0 = returnFunc(ctx, productID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrderItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderItemRepository_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockOrderItemRepository_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockOrderItemRepository_Expecter) GetItem(ctx interface{}, productID interface{}, orderID interface{}) *MockOrderItemRepository_GetItem_Call {
	return &MockOrderItemRepository_GetItem_Call{Call: _e.mock.On("GetItem", ctx, productID, orderID)}
}

func (_c *MockOrderItemRepository_GetItem_Call) Run(run func(ctx context.Context, productID uuid.UUID, orderID uuid.UUID)) *MockOrderItemRepository_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderItemRepository_GetItem_Call) Return(orderItem *models.OrderItem, err error) *MockOrderItemRepository_GetItem_Call {
	_c.Call.Return(orderItem, err)
	return _c
}

func (_c *MockOrderItemRepository_GetItem_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID, orderID uuid.UUID) (*models.OrderItem, error)) *MockOrderItemRepository_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockOrderItemRepository
func (_mock *MockOrderItemRepository) Upsert(ctx context.Context, orderItem *models.OrderItem) error {
	ret := _mock.Called(ctx, orderItem)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.OrderItem) error); ok {
		r0 = returnFunc(ctx, orderItem)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderItemRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockOrderItemRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - orderItem *models.OrderItem
func (_e *MockOrderItemRepository_Expecter) Upsert(ctx interface{}, orderItem interface{}) *MockOrderItemRepository_Upsert_Call {
	return &MockOrderItemRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, orderItem)}
}

func (_c *MockOrderItemRepository_Upsert_Call) Run(run func(ctx context.Context, orderItem *models.OrderItem)) *MockOrderItemRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.OrderItem
		if args[1] != nil {
			arg1 = args[1].(*models.OrderItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderItemRepository_Upsert_Call) Return(err error) *MockOrderItemRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderItemRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, orderItem *models.OrderItem) error) *MockOrderItemRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
