// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasskeyRepository creates a new instance of MockPasskeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasskeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasskeyRepository {
	mock := &MockPasskeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasskeyRepository is an autogenerated mock type for the PasskeyRepository type
type MockPasskeyRepository struct {
	mock.Mock
}

type MockPasskeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasskeyRepository) EXPECT() *MockPasskeyRepository_Expecter {
	return &MockPasskeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPasskeyRepository
func (_mock *MockPasskeyRepository) Create(ctx context.Context, credential *models.PasskeyCredential) error {
	ret := _mock.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.PasskeyCredential) error); ok {
		r0 = returnFunc(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasskeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPasskeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *models.PasskeyCredential
func (_e *MockPasskeyRepository_Expecter) Create(ctx interface{}, credential interface{}) *MockPasskeyRepository_Create_Call {
	return &MockPasskeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, credential)}
}

func (_c *MockPasskeyRepository_Create_Call) Run(run func(ctx context.Context, credential *models.PasskeyCredential)) *MockPasskeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.PasskeyCredential
		if args[1] != nil {
			arg1 = args[1].(*models.PasskeyCredential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasskeyRepository_Create_Call) Return(err error) *MockPasskeyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasskeyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, credential *models.PasskeyCredential) error) *MockPasskeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockPasskeyRepository
func (_mock *MockPasskeyRepository) Delete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasskeyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPasskeyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockPasskeyRepository_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}) *MockPasskeyRepository_Delete_Call {
	return &MockPasskeyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *MockPasskeyRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockPasskeyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPasskeyRepository_Delete_Call) Return(err error) *MockPasskeyRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasskeyRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockPasskeyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCredentialID provides a mock function for the type MockPasskeyRepository
func (_mock *MockPasskeyRepository) GetByCredentialID(ctx context.Context, credentialID []byte) (*models.PasskeyCredential, error) {
	ret := _mock.Called(ctx, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCredentialID")
	}

	var r0 *models.PasskeyCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*models.PasskeyCredential, error)); ok {
		return returnFunc(ctx, credentialID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *models.PasskeyCredential); ok {
		r0 = returnFunc(ctx, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasskeyCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, credentialID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasskeyRepository_GetByCredentialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCredentialID'
type MockPasskeyRepository_GetByCredentialID_Call struct {
	*mock.Call
}

// GetByCredentialID is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID []byte
func (_e *MockPasskeyRepository_Expecter) GetByCredentialID(ctx interface{}, credentialID interface{}) *MockPasskeyRepository_GetByCredentialID_Call {
	return &MockPasskeyRepository_GetByCredentialID_Call{Call: _e.mock.On("GetByCredentialID", ctx, credentialID)}
}

func (_c *MockPasskeyRepository_GetByCredentialID_Call) Run(run func(ctx context.Context, credentialID []byte)) *MockPasskeyRepository_GetByCredentialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasskeyRepository_GetByCredentialID_Call) Return(passkeyCredential *models.PasskeyCredential, err error) *MockPasskeyRepository_GetByCredentialID_Call {
	_c.Call.Return(passkeyCredential, err)
	return _c
}

func (_c *MockPasskeyRepository_GetByCredentialID_Call) RunAndReturn(run func(ctx context.Context, credentialID []byte) (*models.PasskeyCredential, error)) *MockPasskeyRepository_GetByCredentialID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockPasskeyRepository
func (_mock *MockPasskeyRepository) GetByUser(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*models.PasskeyCredential, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 *models.PasskeyCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.PasskeyCredential, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.PasskeyCredential); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasskeyCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasskeyRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockPasskeyRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockPasskeyRepository_Expecter) GetByUser(ctx interface{}, id interface{}, userID interface{}) *MockPasskeyRepository_GetByUser_Call {
	return &MockPasskeyRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, id, userID)}
}

func (_c *MockPasskeyRepository_GetByUser_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockPasskeyRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPasskeyRepository_GetByUser_Call) Return(passkeyCredential *models.PasskeyCredential, err error) *MockPasskeyRepository_GetByUser_Call {
	_c.Call.Return(passkeyCredential, err)
	return _c
}

func (_c *MockPasskeyRepository_GetByUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*models.PasskeyCredential, error)) *MockPasskeyRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetListByUser provides a mock function for the type MockPasskeyRepository
func (_mock *MockPasskeyRepository) GetListByUser(ctx context.Context, userID uuid.UUID) ([]models.PasskeyCredential, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetListByUser")
	}

	var r0 []models.PasskeyCredential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.PasskeyCredential, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.PasskeyCredential); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PasskeyCredential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasskeyRepository_GetListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListByUser'
type MockPasskeyRepository_GetListByUser_Call struct {
	*mock.Call
}

// GetListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockPasskeyRepository_Expecter) GetListByUser(ctx interface{}, userID interface{}) *MockPasskeyRepository_GetListByUser_Call {
	return &MockPasskeyRepository_GetListByUser_Call{Call: _e.mock.On("GetListByUser", ctx, userID)}
}

func (_c *MockPasskeyRepository_GetListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockPasskeyRepository_GetListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasskeyRepository_GetListByUser_Call) Return(passkeyCredentials []models.PasskeyCredential, err error) *MockPasskeyRepository_GetListByUser_Call {
	_c.Call.Return(passkeyCredentials, err)
	return _c
}

func (_c *MockPasskeyRepository_GetListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]models.PasskeyCredential, error)) *MockPasskeyRepository_GetListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPasskeyRepository
func (_mock *MockPasskeyRepository) Update(ctx context.Context, credential *models.PasskeyCredential) error {
	ret := _mock.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.PasskeyCredential) error); ok {
		r0 = returnFunc(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasskeyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPasskeyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *models.PasskeyCredential
func (_e *MockPasskeyRepository_Expecter) Update(ctx interface{}, credential interface{}) *MockPasskeyRepository_Update_Call {
	return &MockPasskeyRepository_Update_Call{Call: _e.mock.On("Update", ctx, credential)}
}

func (_c *MockPasskeyRepository_Update_Call) Run(run func(ctx context.Context, credential *models.PasskeyCredential)) *MockPasskeyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.PasskeyCredential
		if args[1] != nil {
			arg1 = args[1].(*models.PasskeyCredential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasskeyRepository_Update_Call) Return(err error) *MockPasskeyRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasskeyRepository_Update_Call) RunAndReturn(run func(ctx context.Context, credential *models.PasskeyCredential) error) *MockPasskeyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
