// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/dto"
	"go-shop-backend/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Create(ctx context.Context, product *models.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *models.Product
func (_e *MockProductRepository_Expecter) Create(ctx interface{}, product interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(ctx context.Context, product *models.Product)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Product
		if args[1] != nil {
			arg1 = args[1].(*models.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(err error) *MockProductRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(ctx context.Context, product *models.Product) error) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Exists(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockProductRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockProductRepository_Exists_Call {
	return &MockProductRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockProductRepository_Exists_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProductRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Exists_Call) Return(b bool, err error) *MockProductRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockProductRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *MockProductRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetByID(ctx context.Context, id uuid.UUID, preload bool) (*models.Product, error) {
	ret := _mock.Called(ctx, id, preload)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*models.Product, error)); ok {
		return returnFunc(ctx, id, preload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *models.Product); ok {
		r0 = returnFunc(ctx, id, preload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, id, preload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProductRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - preload bool
func (_e *MockProductRepository_Expecter) GetByID(ctx interface{}, id interface{}, preload interface{}) *MockProductRepository_GetByID_Call {
	return &MockProductRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, preload)}
}

func (_c *MockProductRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, preload bool)) *MockProductRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetByID_Call) Return(product *models.Product, err error) *MockProductRepository_GetByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, preload bool) (*models.Product, error)) *MockProductRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) ListProducts(ctx context.Context, req dto.ListProductRequest) ([]*models.Product, int64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []*models.Product
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListProductRequest) ([]*models.Product, int64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListProductRequest) []*models.Product); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ListProductRequest) int64); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, dto.ListProductRequest) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProductRepository_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type MockProductRepository_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.ListProductRequest
func (_e *MockProductRepository_Expecter) ListProducts(ctx interface{}, req interface{}) *MockProductRepository_ListProducts_Call {
	return &MockProductRepository_ListProducts_Call{Call: _e.mock.On("ListProducts", ctx, req)}
}

func (_c *MockProductRepository_ListProducts_Call) Run(run func(ctx context.Context, req dto.ListProductRequest)) *MockProductRepository_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ListProductRequest
		if args[1] != nil {
			arg1 = args[1].(dto.ListProductRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_ListProducts_Call) Return(products []*models.Product, n int64, err error) *MockProductRepository_ListProducts_Call {
	_c.Call.Return(products, n, err)
	return _c
}

func (_c *MockProductRepository_ListProducts_Call) RunAndReturn(run func(ctx context.Context, req dto.ListProductRequest) ([]*models.Product, int64, error)) *MockProductRepository_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Search(ctx context.Context, req dto.SearchProductRequest) ([]*models.Product, int64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*models.Product
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.SearchProductRequest) ([]*models.Product, int64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.SearchProductRequest) []*models.Product); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.SearchProductRequest) int64); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, dto.SearchProductRequest) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProductRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockProductRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.SearchProductRequest
func (_e *MockProductRepository_Expecter) Search(ctx interface{}, req interface{}) *MockProductRepository_Search_Call {
	return &MockProductRepository_Search_Call{Call: _e.mock.On("Search", ctx, req)}
}

func (_c *MockProductRepository_Search_Call) Run(run func(ctx context.Context, req dto.SearchProductRequest)) *MockProductRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.SearchProductRequest
		if args[1] != nil {
			arg1 = args[1].(dto.SearchProductRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Search_Call) Return(products []*models.Product, n int64, err error) *MockProductRepository_Search_Call {
	_c.Call.Return(products, n, err)
	return _c
}

func (_c *MockProductRepository_Search_Call) RunAndReturn(run func(ctx context.Context, req dto.SearchProductRequest) ([]*models.Product, int64, error)) *MockProductRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Update(ctx context.Context, product *models.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - product *models.Product
func (_e *MockProductRepository_Expecter) Update(ctx interface{}, product interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", ctx, product)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(ctx context.Context, product *models.Product)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Product
		if args[1] != nil {
			arg1 = args[1].(*models.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(err error) *MockProductRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(ctx context.Context, product *models.Product) error) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
