// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUploadRepository creates a new instance of MockUploadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadRepository {
	mock := &MockUploadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadRepository is an autogenerated mock type for the UploadRepository type
type MockUploadRepository struct {
	mock.Mock
}

type MockUploadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadRepository) EXPECT() *MockUploadRepository_Expecter {
	return &MockUploadRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUploadRepository
func (_mock *MockUploadRepository) Create(ctx context.Context, req *models.Upload) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Upload) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUploadRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.Upload
func (_e *MockUploadRepository_Expecter) Create(ctx interface{}, req interface{}) *MockUploadRepository_Create_Call {
	return &MockUploadRepository_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockUploadRepository_Create_Call) Run(run func(ctx context.Context, req *models.Upload)) *MockUploadRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Upload
		if args[1] != nil {
			arg1 = args[1].(*models.Upload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadRepository_Create_Call) Return(err error) *MockUploadRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadRepository_Create_Call) RunAndReturn(run func(ctx context.Context, req *models.Upload) error) *MockUploadRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockUploadRepository
func (_mock *MockUploadRepository) Exists(ctx context.Context, objectKey string) (bool, error) {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, objectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, objectKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockUploadRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockUploadRepository_Expecter) Exists(ctx interface{}, objectKey interface{}) *MockUploadRepository_Exists_Call {
	return &MockUploadRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, objectKey)}
}

func (_c *MockUploadRepository_Exists_Call) Run(run func(ctx context.Context, objectKey string)) *MockUploadRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUploadRepository_Exists_Call) Return(b bool, err error) *MockUploadRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUploadRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, objectKey string) (bool, error)) *MockUploadRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}
