// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/pkg/storage"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CreatePresignedPost provides a mock function for the type MockStorage
func (_mock *MockStorage) CreatePresignedPost(ctx context.Context, opts storage.PresignedPostOptions) (*storage.PresignedPost, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreatePresignedPost")
	}

	var r0 *storage.PresignedPost
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.PresignedPostOptions) (*storage.PresignedPost, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.PresignedPostOptions) *storage.PresignedPost); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.PresignedPost)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.PresignedPostOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreatePresignedPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePresignedPost'
type MockStorage_CreatePresignedPost_Call struct {
	*mock.Call
}

// CreatePresignedPost is a helper method to define mock.On call
//   - ctx context.Context
//   - opts storage.PresignedPostOptions
func (_e *MockStorage_Expecter) CreatePresignedPost(ctx interface{}, opts interface{}) *MockStorage_CreatePresignedPost_Call {
	return &MockStorage_CreatePresignedPost_Call{Call: _e.mock.On("CreatePresignedPost", ctx, opts)}
}

func (_c *MockStorage_CreatePresignedPost_Call) Run(run func(ctx context.Context, opts storage.PresignedPostOptions)) *MockStorage_CreatePresignedPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.PresignedPostOptions
		if args[1] != nil {
			arg1 = args[1].(storage.PresignedPostOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CreatePresignedPost_Call) Return(presignedPost *storage.PresignedPost, err error) *MockStorage_CreatePresignedPost_Call {
	_c.Call.Return(presignedPost, err)
	return _c
}

func (_c *MockStorage_CreatePresignedPost_Call) RunAndReturn(run func(ctx context.Context, opts storage.PresignedPostOptions) (*storage.PresignedPost, error)) *MockStorage_CreatePresignedPost_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStorage
func (_mock *MockStorage) Delete(ctx context.Context, objectKey string) error {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockStorage_Expecter) Delete(ctx interface{}, objectKey interface{}) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, objectKey)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, objectKey string)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(err error) *MockStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, objectKey string) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockStorage
func (_mock *MockStorage) Exists(ctx context.Context, objectKey string) error {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockStorage_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockStorage_Expecter) Exists(ctx interface{}, objectKey interface{}) *MockStorage_Exists_Call {
	return &MockStorage_Exists_Call{Call: _e.mock.On("Exists", ctx, objectKey)}
}

func (_c *MockStorage_Exists_Call) Run(run func(ctx context.Context, objectKey string)) *MockStorage_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Exists_Call) Return(err error) *MockStorage_Exists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Exists_Call) RunAndReturn(run func(ctx context.Context, objectKey string) error) *MockStorage_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectInfo provides a mock function for the type MockStorage
func (_mock *MockStorage) GetObjectInfo(ctx context.Context, objectKey string) (*storage.ObjectInfo, error) {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectInfo")
	}

	var r0 *storage.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*storage.ObjectInfo, error)); ok {
		return returnFunc(ctx, objectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *storage.ObjectInfo); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ObjectInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, objectKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetObjectInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectInfo'
type MockStorage_GetObjectInfo_Call struct {
	*mock.Call
}

// GetObjectInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockStorage_Expecter) GetObjectInfo(ctx interface{}, objectKey interface{}) *MockStorage_GetObjectInfo_Call {
	return &MockStorage_GetObjectInfo_Call{Call: _e.mock.On("GetObjectInfo", ctx, objectKey)}
}

func (_c *MockStorage_GetObjectInfo_Call) Run(run func(ctx context.Context, objectKey string)) *MockStorage_GetObjectInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetObjectInfo_Call) Return(objectInfo *storage.ObjectInfo, err error) *MockStorage_GetObjectInfo_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockStorage_GetObjectInfo_Call) RunAndReturn(run func(ctx context.Context, objectKey string) (*storage.ObjectInfo, error)) *MockStorage_GetObjectInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedURL provides a mock function for the type MockStorage
func (_mock *MockStorage) GetPresignedURL(ctx context.Context, objectKey string, expiry time.Duration) (string, error) {
	ret := _mock.Called(ctx, objectKey, expiry)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, objectKey, expiry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, objectKey, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, objectKey, expiry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedURL'
type MockStorage_GetPresignedURL_Call struct {
	*mock.Call
}

// GetPresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
//   - expiry time.Duration
func (_e *MockStorage_Expecter) GetPresignedURL(ctx interface{}, objectKey interface{}, expiry interface{}) *MockStorage_GetPresignedURL_Call {
	return &MockStorage_GetPresignedURL_Call{Call: _e.mock.On("GetPresignedURL", ctx, objectKey, expiry)}
}

func (_c *MockStorage_GetPresignedURL_Call) Run(run func(ctx context.Context, objectKey string, expiry time.Duration)) *MockStorage_GetPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_GetPresignedURL_Call) Return(s string, err error) *MockStorage_GetPresignedURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_GetPresignedURL_Call) RunAndReturn(run func(ctx context.Context, objectKey string, expiry time.Duration) (string, error)) *MockStorage_GetPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockStorage
func (_mock *MockStorage) Open(ctx context.Context, objectKey string) (io.ReadSeekCloser, error) {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 io.ReadSeekCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadSeekCloser, error)); ok {
		return returnFunc(ctx, objectKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadSeekCloser); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeekCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, objectKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockStorage_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockStorage_Expecter) Open(ctx interface{}, objectKey interface{}) *MockStorage_Open_Call {
	return &MockStorage_Open_Call{Call: _e.mock.On("Open", ctx, objectKey)}
}

func (_c *MockStorage_Open_Call) Run(run func(ctx context.Context, objectKey string)) *MockStorage_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Open_Call) Return(readSeekCloser io.ReadSeekCloser, err error) *MockStorage_Open_Call {
	_c.Call.Return(readSeekCloser, err)
	return _c
}

func (_c *MockStorage_Open_Call) RunAndReturn(run func(ctx context.Context, objectKey string) (io.ReadSeekCloser, error)) *MockStorage_Open_Call {
	_c.Call.Return(run)
	return _c
}

// PublicURL provides a mock function for the type MockStorage
func (_mock *MockStorage) PublicURL(ctx context.Context, objectKey string) string {
	ret := _mock.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for PublicURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, objectKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStorage_PublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicURL'
type MockStorage_PublicURL_Call struct {
	*mock.Call
}

// PublicURL is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockStorage_Expecter) PublicURL(ctx interface{}, objectKey interface{}) *MockStorage_PublicURL_Call {
	return &MockStorage_PublicURL_Call{Call: _e.mock.On("PublicURL", ctx, objectKey)}
}

func (_c *MockStorage_PublicURL_Call) Run(run func(ctx context.Context, objectKey string)) *MockStorage_PublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_PublicURL_Call) Return(s string) *MockStorage_PublicURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStorage_PublicURL_Call) RunAndReturn(run func(ctx context.Context, objectKey string) string) *MockStorage_PublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockStorage
func (_mock *MockStorage) Upload(ctx context.Context, objectKey string, r io.Reader, size int64, opts storage.UploadOptions) (string, error) {
	ret := _mock.Called(ctx, objectKey, r, size, opts)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, storage.UploadOptions) (string, error)); ok {
		return returnFunc(ctx, objectKey, r, size, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, storage.UploadOptions) string); ok {
		r0 = returnFunc(ctx, objectKey, r, size, opts)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64, storage.UploadOptions) error); ok {
		r1 = returnFunc(ctx, objectKey, r, size, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
//   - r io.Reader
//   - size int64
//   - opts storage.UploadOptions
func (_e *MockStorage_Expecter) Upload(ctx interface{}, objectKey interface{}, r interface{}, size interface{}, opts interface{}) *MockStorage_Upload_Call {
	return &MockStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, objectKey, r, size, opts)}
}

func (_c *MockStorage_Upload_Call) Run(run func(ctx context.Context, objectKey string, r io.Reader, size int64, opts storage.UploadOptions)) *MockStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 storage.UploadOptions
		if args[4] != nil {
			arg4 = args[4].(storage.UploadOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorage_Upload_Call) Return(s string, err error) *MockStorage_Upload_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_Upload_Call) RunAndReturn(run func(ctx context.Context, objectKey string, r io.Reader, size int64, opts storage.UploadOptions) (string, error)) *MockStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}
