// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationTask creates a new instance of MockNotificationTask. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationTask {
	mock := &MockNotificationTask{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationTask is an autogenerated mock type for the NotificationTask type
type MockNotificationTask struct {
	mock.Mock
}

type MockNotificationTask_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationTask) EXPECT() *MockNotificationTask_Expecter {
	return &MockNotificationTask_Expecter{mock: &_m.Mock}
}

// SendEmailConfirmationCode provides a mock function for the type MockNotificationTask
func (_mock *MockNotificationTask) SendEmailConfirmationCode(ctx context.Context, email string, code string) error {
	ret := _mock.Called(ctx, email, code)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailConfirmationCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationTask_SendEmailConfirmationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailConfirmationCode'
type MockNotificationTask_SendEmailConfirmationCode_Call struct {
	*mock.Call
}

// SendEmailConfirmationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
func (_e *MockNotificationTask_Expecter) SendEmailConfirmationCode(ctx interface{}, email interface{}, code interface{}) *MockNotificationTask_SendEmailConfirmationCode_Call {
	return &MockNotificationTask_SendEmailConfirmationCode_Call{Call: _e.mock.On("SendEmailConfirmationCode", ctx, email, code)}
}

func (_c *MockNotificationTask_SendEmailConfirmationCode_Call) Run(run func(ctx context.Context, email string, code string)) *MockNotificationTask_SendEmailConfirmationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationTask_SendEmailConfirmationCode_Call) Return(err error) *MockNotificationTask_SendEmailConfirmationCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationTask_SendEmailConfirmationCode_Call) RunAndReturn(run func(ctx context.Context, email string, code string) error) *MockNotificationTask_SendEmailConfirmationCode_Call {
	_c.Call.Return(run)
	return _c
}
