// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/tasks"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderTask creates a new instance of MockOrderTask. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderTask {
	mock := &MockOrderTask{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderTask is an autogenerated mock type for the OrderTask type
type MockOrderTask struct {
	mock.Mock
}

type MockOrderTask_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderTask) EXPECT() *MockOrderTask_Expecter {
	return &MockOrderTask_Expecter{mock: &_m.Mock}
}

// EnqueueCancelOrder provides a mock function for the type MockOrderTask
func (_mock *MockOrderTask) EnqueueCancelOrder(ctx context.Context, payload tasks.CancelOrderPayload, delay time.Duration) error {
	ret := _mock.Called(ctx, payload, delay)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueCancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tasks.CancelOrderPayload, time.Duration) error); ok {
		r0 = returnFunc(ctx, payload, delay)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderTask_EnqueueCancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueCancelOrder'
type MockOrderTask_EnqueueCancelOrder_Call struct {
	*mock.Call
}

// EnqueueCancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - payload tasks.CancelOrderPayload
//   - delay time.Duration
func (_e *MockOrderTask_Expecter) EnqueueCancelOrder(ctx interface{}, payload interface{}, delay interface{}) *MockOrderTask_EnqueueCancelOrder_Call {
	return &MockOrderTask_EnqueueCancelOrder_Call{Call: _e.mock.On("EnqueueCancelOrder", ctx, payload, delay)}
}

func (_c *MockOrderTask_EnqueueCancelOrder_Call) Run(run func(ctx context.Context, payload tasks.CancelOrderPayload, delay time.Duration)) *MockOrderTask_EnqueueCancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tasks.CancelOrderPayload
		if args[1] != nil {
			arg1 = args[1].(tasks.CancelOrderPayload)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderTask_EnqueueCancelOrder_Call) Return(err error) *MockOrderTask_EnqueueCancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderTask_EnqueueCancelOrder_Call) RunAndReturn(run func(ctx context.Context, payload tasks.CancelOrderPayload, delay time.Duration) error) *MockOrderTask_EnqueueCancelOrder_Call {
	_c.Call.Return(run)
	return _c
}
