// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAddressService creates a new instance of MockAddressService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddressService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddressService {
	mock := &MockAddressService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAddressService is an autogenerated mock type for the AddressService type
type MockAddressService struct {
	mock.Mock
}

type MockAddressService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddressService) EXPECT() *MockAddressService_Expecter {
	return &MockAddressService_Expecter{mock: &_m.Mock}
}

// CreateAddress provides a mock function for the type MockAddressService
func (_mock *MockAddressService) CreateAddress(ctx context.Context, userID uuid.UUID, req dto.CreateAddressRequest) (*dto.AddressResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAddress")
	}

	var r0 *dto.AddressResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateAddressRequest) (*dto.AddressResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateAddressRequest) *dto.AddressResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AddressResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateAddressRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAddressService_CreateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAddress'
type MockAddressService_CreateAddress_Call struct {
	*mock.Call
}

// CreateAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.CreateAddressRequest
func (_e *MockAddressService_Expecter) CreateAddress(ctx interface{}, userID interface{}, req interface{}) *MockAddressService_CreateAddress_Call {
	return &MockAddressService_CreateAddress_Call{Call: _e.mock.On("CreateAddress", ctx, userID, req)}
}

func (_c *MockAddressService_CreateAddress_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.CreateAddressRequest)) *MockAddressService_CreateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.CreateAddressRequest
		if args[2] != nil {
			arg2 = args[2].(dto.CreateAddressRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAddressService_CreateAddress_Call) Return(addressResponse *dto.AddressResponse, err error) *MockAddressService_CreateAddress_Call {
	_c.Call.Return(addressResponse, err)
	return _c
}

func (_c *MockAddressService_CreateAddress_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.CreateAddressRequest) (*dto.AddressResponse, error)) *MockAddressService_CreateAddress_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAddress provides a mock function for the type MockAddressService
func (_mock *MockAddressService) DeleteAddress(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAddress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAddressService_DeleteAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAddress'
type MockAddressService_DeleteAddress_Call struct {
	*mock.Call
}

// DeleteAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockAddressService_Expecter) DeleteAddress(ctx interface{}, id interface{}, userID interface{}) *MockAddressService_DeleteAddress_Call {
	return &MockAddressService_DeleteAddress_Call{Call: _e.mock.On("DeleteAddress", ctx, id, userID)}
}

func (_c *MockAddressService_DeleteAddress_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockAddressService_DeleteAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAddressService_DeleteAddress_Call) Return(err error) *MockAddressService_DeleteAddress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAddressService_DeleteAddress_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockAddressService_DeleteAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetAddress provides a mock function for the type MockAddressService
func (_mock *MockAddressService) GetAddress(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*dto.AddressResponse, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAddress")
	}

	var r0 *dto.AddressResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.AddressResponse, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.AddressResponse); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AddressResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAddressService_GetAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddress'
type MockAddressService_GetAddress_Call struct {
	*mock.Call
}

// GetAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockAddressService_Expecter) GetAddress(ctx interface{}, id interface{}, userID interface{}) *MockAddressService_GetAddress_Call {
	return &MockAddressService_GetAddress_Call{Call: _e.mock.On("GetAddress", ctx, id, userID)}
}

func (_c *MockAddressService_GetAddress_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockAddressService_GetAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAddressService_GetAddress_Call) Return(addressResponse *dto.AddressResponse, err error) *MockAddressService_GetAddress_Call {
	_c.Call.Return(addressResponse, err)
	return _c
}

func (_c *MockAddressService_GetAddress_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*dto.AddressResponse, error)) *MockAddressService_GetAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ListAddresses provides a mock function for the type MockAddressService
func (_mock *MockAddressService) ListAddresses(ctx context.Context, userID uuid.UUID) ([]*dto.AddressResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAddresses")
	}

	var r0 []*dto.AddressResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*dto.AddressResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*dto.AddressResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.AddressResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAddressService_ListAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAddresses'
type MockAddressService_ListAddresses_Call struct {
	*mock.Call
}

// ListAddresses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAddressService_Expecter) ListAddresses(ctx interface{}, userID interface{}) *MockAddressService_ListAddresses_Call {
	return &MockAddressService_ListAddresses_Call{Call: _e.mock.On("ListAddresses", ctx, userID)}
}

func (_c *MockAddressService_ListAddresses_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAddressService_ListAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAddressService_ListAddresses_Call) Return(addressResponses []*dto.AddressResponse, err error) *MockAddressService_ListAddresses_Call {
	_c.Call.Return(addressResponses, err)
	return _c
}

func (_c *MockAddressService_ListAddresses_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*dto.AddressResponse, error)) *MockAddressService_ListAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefault provides a mock function for the type MockAddressService
func (_mock *MockAddressService) SetDefault(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefault")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAddressService_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type MockAddressService_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockAddressService_Expecter) SetDefault(ctx interface{}, id interface{}, userID interface{}) *MockAddressService_SetDefault_Call {
	return &MockAddressService_SetDefault_Call{Call: _e.mock.On("SetDefault", ctx, id, userID)}
}

func (_c *MockAddressService_SetDefault_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockAddressService_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAddressService_SetDefault_Call) Return(err error) *MockAddressService_SetDefault_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAddressService_SetDefault_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockAddressService_SetDefault_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAddress provides a mock function for the type MockAddressService
func (_mock *MockAddressService) UpdateAddress(ctx context.Context, id uuid.UUID, userID uuid.UUID, req dto.UpdateAddressRequest) (*dto.AddressResponse, error) {
	ret := _mock.Called(ctx, id, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddress")
	}

	var r0 *dto.AddressResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateAddressRequest) (*dto.AddressResponse, error)); ok {
		return returnFunc(ctx, id, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateAddressRequest) *dto.AddressResponse); ok {
		r0 = returnFunc(ctx, id, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AddressResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateAddressRequest) error); ok {
		r1 = returnFunc(ctx, id, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAddressService_UpdateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAddress'
type MockAddressService_UpdateAddress_Call struct {
	*mock.Call
}

// UpdateAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - req dto.UpdateAddressRequest
func (_e *MockAddressService_Expecter) UpdateAddress(ctx interface{}, id interface{}, userID interface{}, req interface{}) *MockAddressService_UpdateAddress_Call {
	return &MockAddressService_UpdateAddress_Call{Call: _e.mock.On("UpdateAddress", ctx, id, userID, req)}
}

func (_c *MockAddressService_UpdateAddress_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, req dto.UpdateAddressRequest)) *MockAddressService_UpdateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.UpdateAddressRequest
		if args[3] != nil {
			arg3 = args[3].(dto.UpdateAddressRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAddressService_UpdateAddress_Call) Return(addressResponse *dto.AddressResponse, err error) *MockAddressService_UpdateAddress_Call {
	_c.Call.Return(addressResponse, err)
	return _c
}

func (_c *MockAddressService_UpdateAddress_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, req dto.UpdateAddressRequest) (*dto.AddressResponse, error)) *MockAddressService_UpdateAddress_Call {
	_c.Call.Return(run)
	return _c
}
