// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryService creates a new instance of MockCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryService {
	mock := &MockCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryService is an autogenerated mock type for the CategoryService type
type MockCategoryService struct {
	mock.Mock
}

type MockCategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryService) EXPECT() *MockCategoryService_Expecter {
	return &MockCategoryService_Expecter{mock: &_m.Mock}
}

// ListCategories provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) ListCategories(ctx context.Context, req dto.ListCategoryRequest) ([]*dto.ProductCategoryResponse, int64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []*dto.ProductCategoryResponse
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListCategoryRequest) ([]*dto.ProductCategoryResponse, int64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListCategoryRequest) []*dto.ProductCategoryResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ProductCategoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ListCategoryRequest) int64); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, dto.ListCategoryRequest) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCategoryService_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockCategoryService_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.ListCategoryRequest
func (_e *MockCategoryService_Expecter) ListCategories(ctx interface{}, req interface{}) *MockCategoryService_ListCategories_Call {
	return &MockCategoryService_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx, req)}
}

func (_c *MockCategoryService_ListCategories_Call) Run(run func(ctx context.Context, req dto.ListCategoryRequest)) *MockCategoryService_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ListCategoryRequest
		if args[1] != nil {
			arg1 = args[1].(dto.ListCategoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryService_ListCategories_Call) Return(productCategoryResponses []*dto.ProductCategoryResponse, n int64, err error) *MockCategoryService_ListCategories_Call {
	_c.Call.Return(productCategoryResponses, n, err)
	return _c
}

func (_c *MockCategoryService_ListCategories_Call) RunAndReturn(run func(ctx context.Context, req dto.ListCategoryRequest) ([]*dto.ProductCategoryResponse, int64, error)) *MockCategoryService_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}
