// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFavoriteService creates a new instance of MockFavoriteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteService {
	mock := &MockFavoriteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFavoriteService is an autogenerated mock type for the FavoriteService type
type MockFavoriteService struct {
	mock.Mock
}

type MockFavoriteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteService) EXPECT() *MockFavoriteService_Expecter {
	return &MockFavoriteService_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function for the type MockFavoriteService
func (_mock *MockFavoriteService) AddProduct(ctx context.Context, userID uuid.UUID, productID uuid.UUID) ([]*dto.FavoriteProduct, int64, error) {
	ret := _mock.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 []*dto.FavoriteProduct
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*dto.FavoriteProduct, int64, error)); ok {
		return returnFunc(ctx, userID, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*dto.FavoriteProduct); ok {
		r0 = returnFunc(ctx, userID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.FavoriteProduct)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) int64); ok {
		r1 = returnFunc(ctx, userID, productID)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, userID, productID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFavoriteService_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type MockFavoriteService_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
func (_e *MockFavoriteService_Expecter) AddProduct(ctx interface{}, userID interface{}, productID interface{}) *MockFavoriteService_AddProduct_Call {
	return &MockFavoriteService_AddProduct_Call{Call: _e.mock.On("AddProduct", ctx, userID, productID)}
}

func (_c *MockFavoriteService_AddProduct_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID)) *MockFavoriteService_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavoriteService_AddProduct_Call) Return(favoriteProducts []*dto.FavoriteProduct, n int64, err error) *MockFavoriteService_AddProduct_Call {
	_c.Call.Return(favoriteProducts, n, err)
	return _c
}

func (_c *MockFavoriteService_AddProduct_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID) ([]*dto.FavoriteProduct, int64, error)) *MockFavoriteService_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// IsFavorite provides a mock function for the type MockFavoriteService
func (_mock *MockFavoriteService) IsFavorite(ctx context.Context, userID uuid.UUID, productID uuid.UUID) (*dto.FavoriteStatusResponse, error) {
	ret := _mock.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for IsFavorite")
	}

	var r0 *dto.FavoriteStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.FavoriteStatusResponse, error)); ok {
		return returnFunc(ctx, userID, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.FavoriteStatusResponse); ok {
		r0 = returnFunc(ctx, userID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FavoriteStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFavoriteService_IsFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFavorite'
type MockFavoriteService_IsFavorite_Call struct {
	*mock.Call
}

// IsFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
func (_e *MockFavoriteService_Expecter) IsFavorite(ctx interface{}, userID interface{}, productID interface{}) *MockFavoriteService_IsFavorite_Call {
	return &MockFavoriteService_IsFavorite_Call{Call: _e.mock.On("IsFavorite", ctx, userID, productID)}
}

func (_c *MockFavoriteService_IsFavorite_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID)) *MockFavoriteService_IsFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavoriteService_IsFavorite_Call) Return(favoriteStatusResponse *dto.FavoriteStatusResponse, err error) *MockFavoriteService_IsFavorite_Call {
	_c.Call.Return(favoriteStatusResponse, err)
	return _c
}

func (_c *MockFavoriteService_IsFavorite_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID) (*dto.FavoriteStatusResponse, error)) *MockFavoriteService_IsFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFavoriteService
func (_mock *MockFavoriteService) List(ctx context.Context, userID uuid.UUID) ([]*dto.FavoriteProduct, int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*dto.FavoriteProduct
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*dto.FavoriteProduct, int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*dto.FavoriteProduct); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.FavoriteProduct)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) int64); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFavoriteService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFavoriteService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockFavoriteService_Expecter) List(ctx interface{}, userID interface{}) *MockFavoriteService_List_Call {
	return &MockFavoriteService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockFavoriteService_List_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockFavoriteService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFavoriteService_List_Call) Return(favoriteProducts []*dto.FavoriteProduct, n int64, err error) *MockFavoriteService_List_Call {
	_c.Call.Return(favoriteProducts, n, err)
	return _c
}

func (_c *MockFavoriteService_List_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*dto.FavoriteProduct, int64, error)) *MockFavoriteService_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProduct provides a mock function for the type MockFavoriteService
func (_mock *MockFavoriteService) RemoveProduct(ctx context.Context, userID uuid.UUID, productID uuid.UUID) ([]*dto.FavoriteProduct, int64, error) {
	ret := _mock.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProduct")
	}

	var r0 []*dto.FavoriteProduct
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*dto.FavoriteProduct, int64, error)); ok {
		return returnFunc(ctx, userID, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*dto.FavoriteProduct); ok {
		r0 = returnFunc(ctx, userID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.FavoriteProduct)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) int64); ok {
		r1 = returnFunc(ctx, userID, productID)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, userID, productID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFavoriteService_RemoveProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProduct'
type MockFavoriteService_RemoveProduct_Call struct {
	*mock.Call
}

// RemoveProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
func (_e *MockFavoriteService_Expecter) RemoveProduct(ctx interface{}, userID interface{}, productID interface{}) *MockFavoriteService_RemoveProduct_Call {
	return &MockFavoriteService_RemoveProduct_Call{Call: _e.mock.On("RemoveProduct", ctx, userID, productID)}
}

func (_c *MockFavoriteService_RemoveProduct_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID)) *MockFavoriteService_RemoveProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFavoriteService_RemoveProduct_Call) Return(favoriteProducts []*dto.FavoriteProduct, n int64, err error) *MockFavoriteService_RemoveProduct_Call {
	_c.Call.Return(favoriteProducts, n, err)
	return _c
}

func (_c *MockFavoriteService_RemoveProduct_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID) ([]*dto.FavoriteProduct, int64, error)) *MockFavoriteService_RemoveProduct_Call {
	_c.Call.Return(run)
	return _c
}
