// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/dto"
	"go-shop-backend/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryService creates a new instance of MockInventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryService {
	mock := &MockInventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryService is an autogenerated mock type for the InventoryService type
type MockInventoryService struct {
	mock.Mock
}

type MockInventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryService) EXPECT() *MockInventoryService_Expecter {
	return &MockInventoryService_Expecter{mock: &_m.Mock}
}

// CheckProduct provides a mock function for the type MockInventoryService
func (_mock *MockInventoryService) CheckProduct(ctx context.Context, productID uuid.UUID, quantity int) (*models.Product, error) {
	ret := _mock.Called(ctx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for CheckProduct")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*models.Product, error)); ok {
		return returnFunc(ctx, productID, quantity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *models.Product); ok {
		r0 = returnFunc(ctx, productID, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, productID, quantity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryService_CheckProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckProduct'
type MockInventoryService_CheckProduct_Call struct {
	*mock.Call
}

// CheckProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - quantity int
func (_e *MockInventoryService_Expecter) CheckProduct(ctx interface{}, productID interface{}, quantity interface{}) *MockInventoryService_CheckProduct_Call {
	return &MockInventoryService_CheckProduct_Call{Call: _e.mock.On("CheckProduct", ctx, productID, quantity)}
}

func (_c *MockInventoryService_CheckProduct_Call) Run(run func(ctx context.Context, productID uuid.UUID, quantity int)) *MockInventoryService_CheckProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInventoryService_CheckProduct_Call) Return(product *models.Product, err error) *MockInventoryService_CheckProduct_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockInventoryService_CheckProduct_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID, quantity int) (*models.Product, error)) *MockInventoryService_CheckProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeductItems provides a mock function for the type MockInventoryService
func (_mock *MockInventoryService) DeductItems(ctx context.Context, items []dto.InventoryItem) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for DeductItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []dto.InventoryItem) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryService_DeductItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeductItems'
type MockInventoryService_DeductItems_Call struct {
	*mock.Call
}

// DeductItems is a helper method to define mock.On call
//   - ctx context.Context
//   - items []dto.InventoryItem
func (_e *MockInventoryService_Expecter) DeductItems(ctx interface{}, items interface{}) *MockInventoryService_DeductItems_Call {
	return &MockInventoryService_DeductItems_Call{Call: _e.mock.On("DeductItems", ctx, items)}
}

func (_c *MockInventoryService_DeductItems_Call) Run(run func(ctx context.Context, items []dto.InventoryItem)) *MockInventoryService_DeductItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []dto.InventoryItem
		if args[1] != nil {
			arg1 = args[1].([]dto.InventoryItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryService_DeductItems_Call) Return(err error) *MockInventoryService_DeductItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryService_DeductItems_Call) RunAndReturn(run func(ctx context.Context, items []dto.InventoryItem) error) *MockInventoryService_DeductItems_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseItems provides a mock function for the type MockInventoryService
func (_mock *MockInventoryService) ReleaseItems(ctx context.Context, items []dto.InventoryItem) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []dto.InventoryItem) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryService_ReleaseItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseItems'
type MockInventoryService_ReleaseItems_Call struct {
	*mock.Call
}

// ReleaseItems is a helper method to define mock.On call
//   - ctx context.Context
//   - items []dto.InventoryItem
func (_e *MockInventoryService_Expecter) ReleaseItems(ctx interface{}, items interface{}) *MockInventoryService_ReleaseItems_Call {
	return &MockInventoryService_ReleaseItems_Call{Call: _e.mock.On("ReleaseItems", ctx, items)}
}

func (_c *MockInventoryService_ReleaseItems_Call) Run(run func(ctx context.Context, items []dto.InventoryItem)) *MockInventoryService_ReleaseItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []dto.InventoryItem
		if args[1] != nil {
			arg1 = args[1].([]dto.InventoryItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryService_ReleaseItems_Call) Return(err error) *MockInventoryService_ReleaseItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryService_ReleaseItems_Call) RunAndReturn(run func(ctx context.Context, items []dto.InventoryItem) error) *MockInventoryService_ReleaseItems_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveItems provides a mock function for the type MockInventoryService
func (_mock *MockInventoryService) ReserveItems(ctx context.Context, items []dto.InventoryItem) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for ReserveItems")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []dto.InventoryItem) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryService_ReserveItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveItems'
type MockInventoryService_ReserveItems_Call struct {
	*mock.Call
}

// ReserveItems is a helper method to define mock.On call
//   - ctx context.Context
//   - items []dto.InventoryItem
func (_e *MockInventoryService_Expecter) ReserveItems(ctx interface{}, items interface{}) *MockInventoryService_ReserveItems_Call {
	return &MockInventoryService_ReserveItems_Call{Call: _e.mock.On("ReserveItems", ctx, items)}
}

func (_c *MockInventoryService_ReserveItems_Call) Run(run func(ctx context.Context, items []dto.InventoryItem)) *MockInventoryService_ReserveItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []dto.InventoryItem
		if args[1] != nil {
			arg1 = args[1].([]dto.InventoryItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryService_ReserveItems_Call) Return(err error) *MockInventoryService_ReserveItems_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryService_ReserveItems_Call) RunAndReturn(run func(ctx context.Context, items []dto.InventoryItem) error) *MockInventoryService_ReserveItems_Call {
	_c.Call.Return(run)
	return _c
}
