// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function for the type MockOrderService
func (_mock *MockOrderService) AddItem(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID, req dto.AddOrderItemRequest) (*dto.OrderResponse, error) {
	ret := _mock.Called(ctx, userID, sessionID, orderID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 *dto.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID, dto.AddOrderItemRequest) (*dto.OrderResponse, error)); ok {
		return returnFunc(ctx, userID, sessionID, orderID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID, dto.AddOrderItemRequest) *dto.OrderResponse); ok {
		r0 = returnFunc(ctx, userID, sessionID, orderID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID, dto.AddOrderItemRequest) error); ok {
		r1 = returnFunc(ctx, userID, sessionID, orderID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockOrderService_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *uuid.UUID
//   - sessionID uuid.UUID
//   - orderID uuid.UUID
//   - req dto.AddOrderItemRequest
func (_e *MockOrderService_Expecter) AddItem(ctx interface{}, userID interface{}, sessionID interface{}, orderID interface{}, req interface{}) *MockOrderService_AddItem_Call {
	return &MockOrderService_AddItem_Call{Call: _e.mock.On("AddItem", ctx, userID, sessionID, orderID, req)}
}

func (_c *MockOrderService_AddItem_Call) Run(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID, req dto.AddOrderItemRequest)) *MockOrderService_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 dto.AddOrderItemRequest
		if args[4] != nil {
			arg4 = args[4].(dto.AddOrderItemRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrderService_AddItem_Call) Return(orderResponse *dto.OrderResponse, err error) *MockOrderService_AddItem_Call {
	_c.Call.Return(orderResponse, err)
	return _c
}

func (_c *MockOrderService_AddItem_Call) RunAndReturn(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID, req dto.AddOrderItemRequest) (*dto.OrderResponse, error)) *MockOrderService_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function for the type MockOrderService
func (_mock *MockOrderService) Clear(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID) (*dto.OrderResponse, error) {
	ret := _mock.Called(ctx, userID, sessionID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 *dto.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID) (*dto.OrderResponse, error)); ok {
		return returnFunc(ctx, userID, sessionID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID) *dto.OrderResponse); ok {
		r0 = returnFunc(ctx, userID, sessionID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, sessionID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockOrderService_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *uuid.UUID
//   - sessionID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockOrderService_Expecter) Clear(ctx interface{}, userID interface{}, sessionID interface{}, orderID interface{}) *MockOrderService_Clear_Call {
	return &MockOrderService_Clear_Call{Call: _e.mock.On("Clear", ctx, userID, sessionID, orderID)}
}

func (_c *MockOrderService_Clear_Call) Run(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID)) *MockOrderService_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderService_Clear_Call) Return(orderResponse *dto.OrderResponse, err error) *MockOrderService_Clear_Call {
	_c.Call.Return(orderResponse, err)
	return _c
}

func (_c *MockOrderService_Clear_Call) RunAndReturn(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID) (*dto.OrderResponse, error)) *MockOrderService_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) CreateOrder(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID) (*dto.OrderResponse, error) {
	ret := _mock.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *dto.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID) (*dto.OrderResponse, error)); ok {
		return returnFunc(ctx, userID, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID) *dto.OrderResponse); ok {
		r0 = returnFunc(ctx, userID, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *uuid.UUID
//   - sessionID uuid.UUID
func (_e *MockOrderService_Expecter) CreateOrder(ctx interface{}, userID interface{}, sessionID interface{}) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, sessionID)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(orderResponse *dto.OrderResponse, err error) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(orderResponse, err)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID) (*dto.OrderResponse, error)) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockOrderService
func (_mock *MockOrderService) DeleteItem(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID, itemID uuid.UUID) (*dto.OrderResponse, error) {
	ret := _mock.Called(ctx, userID, sessionID, orderID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 *dto.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID, uuid.UUID) (*dto.OrderResponse, error)); ok {
		return returnFunc(ctx, userID, sessionID, orderID, itemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID, uuid.UUID) *dto.OrderResponse); ok {
		r0 = returnFunc(ctx, userID, sessionID, orderID, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, sessionID, orderID, itemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockOrderService_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *uuid.UUID
//   - sessionID uuid.UUID
//   - orderID uuid.UUID
//   - itemID uuid.UUID
func (_e *MockOrderService_Expecter) DeleteItem(ctx interface{}, userID interface{}, sessionID interface{}, orderID interface{}, itemID interface{}) *MockOrderService_DeleteItem_Call {
	return &MockOrderService_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, userID, sessionID, orderID, itemID)}
}

func (_c *MockOrderService_DeleteItem_Call) Run(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID, itemID uuid.UUID)) *MockOrderService_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrderService_DeleteItem_Call) Return(orderResponse *dto.OrderResponse, err error) *MockOrderService_DeleteItem_Call {
	_c.Call.Return(orderResponse, err)
	return _c
}

func (_c *MockOrderService_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID, itemID uuid.UUID) (*dto.OrderResponse, error)) *MockOrderService_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) GetOrder(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID) (*dto.OrderResponse, error) {
	ret := _mock.Called(ctx, userID, sessionID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *dto.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID) (*dto.OrderResponse, error)); ok {
		return returnFunc(ctx, userID, sessionID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID) *dto.OrderResponse); ok {
		r0 = returnFunc(ctx, userID, sessionID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, sessionID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *uuid.UUID
//   - sessionID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockOrderService_Expecter) GetOrder(ctx interface{}, userID interface{}, sessionID interface{}, orderID interface{}) *MockOrderService_GetOrder_Call {
	return &MockOrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, userID, sessionID, orderID)}
}

func (_c *MockOrderService_GetOrder_Call) Run(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID)) *MockOrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderService_GetOrder_Call) Return(orderResponse *dto.OrderResponse, err error) *MockOrderService_GetOrder_Call {
	_c.Call.Return(orderResponse, err)
	return _c
}

func (_c *MockOrderService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, orderID uuid.UUID) (*dto.OrderResponse, error)) *MockOrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function for the type MockOrderService
func (_mock *MockOrderService) GetOrders(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, req dto.ListOrderRequest) ([]*dto.OrderResponse, int64, error) {
	ret := _mock.Called(ctx, userID, sessionID, req)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []*dto.OrderResponse
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, dto.ListOrderRequest) ([]*dto.OrderResponse, int64, error)); ok {
		return returnFunc(ctx, userID, sessionID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, uuid.UUID, dto.ListOrderRequest) []*dto.OrderResponse); ok {
		r0 = returnFunc(ctx, userID, sessionID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, uuid.UUID, dto.ListOrderRequest) int64); ok {
		r1 = returnFunc(ctx, userID, sessionID, req)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *uuid.UUID, uuid.UUID, dto.ListOrderRequest) error); ok {
		r2 = returnFunc(ctx, userID, sessionID, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOrderService_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockOrderService_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *uuid.UUID
//   - sessionID uuid.UUID
//   - req dto.ListOrderRequest
func (_e *MockOrderService_Expecter) GetOrders(ctx interface{}, userID interface{}, sessionID interface{}, req interface{}) *MockOrderService_GetOrders_Call {
	return &MockOrderService_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx, userID, sessionID, req)}
}

func (_c *MockOrderService_GetOrders_Call) Run(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, req dto.ListOrderRequest)) *MockOrderService_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.ListOrderRequest
		if args[3] != nil {
			arg3 = args[3].(dto.ListOrderRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderService_GetOrders_Call) Return(orderResponses []*dto.OrderResponse, n int64, err error) *MockOrderService_GetOrders_Call {
	_c.Call.Return(orderResponses, n, err)
	return _c
}

func (_c *MockOrderService_GetOrders_Call) RunAndReturn(run func(ctx context.Context, userID *uuid.UUID, sessionID uuid.UUID, req dto.ListOrderRequest) ([]*dto.OrderResponse, int64, error)) *MockOrderService_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}
