// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProductChecker creates a new instance of MockProductChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductChecker {
	mock := &MockProductChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductChecker is an autogenerated mock type for the ProductChecker type
type MockProductChecker struct {
	mock.Mock
}

type MockProductChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductChecker) EXPECT() *MockProductChecker_Expecter {
	return &MockProductChecker_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockProductChecker
func (_mock *MockProductChecker) Exists(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductChecker_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockProductChecker_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProductChecker_Expecter) Exists(ctx interface{}, id interface{}) *MockProductChecker_Exists_Call {
	return &MockProductChecker_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockProductChecker_Exists_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProductChecker_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductChecker_Exists_Call) Return(b bool, err error) *MockProductChecker_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockProductChecker_Exists_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *MockProductChecker_Exists_Call {
	_c.Call.Return(run)
	return _c
}
