// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// ConfirmEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) ConfirmEmail(ctx context.Context, userID uuid.UUID, req dto.ConfirmEmailRequest) (*dto.ConfirmEmailResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmEmail")
	}

	var r0 *dto.ConfirmEmailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ConfirmEmailRequest) (*dto.ConfirmEmailResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ConfirmEmailRequest) *dto.ConfirmEmailResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ConfirmEmailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.ConfirmEmailRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ConfirmEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmEmail'
type MockUserService_ConfirmEmail_Call struct {
	*mock.Call
}

// ConfirmEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.ConfirmEmailRequest
func (_e *MockUserService_Expecter) ConfirmEmail(ctx interface{}, userID interface{}, req interface{}) *MockUserService_ConfirmEmail_Call {
	return &MockUserService_ConfirmEmail_Call{Call: _e.mock.On("ConfirmEmail", ctx, userID, req)}
}

func (_c *MockUserService_ConfirmEmail_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.ConfirmEmailRequest)) *MockUserService_ConfirmEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.ConfirmEmailRequest
		if args[2] != nil {
			arg2 = args[2].(dto.ConfirmEmailRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_ConfirmEmail_Call) Return(confirmEmailResponse *dto.ConfirmEmailResponse, err error) *MockUserService_ConfirmEmail_Call {
	_c.Call.Return(confirmEmailResponse, err)
	return _c
}

func (_c *MockUserService_ConfirmEmail_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.ConfirmEmailRequest) (*dto.ConfirmEmailResponse, error)) *MockUserService_ConfirmEmail_Call {
	_c.Call.Return(run)
	return _c
}

// EmailConfirmation provides a mock function for the type MockUserService
func (_mock *MockUserService) EmailConfirmation(ctx context.Context, userID uuid.UUID) (*dto.EmailConfirmationResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for EmailConfirmation")
	}

	var r0 *dto.EmailConfirmationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.EmailConfirmationResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.EmailConfirmationResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.EmailConfirmationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_EmailConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailConfirmation'
type MockUserService_EmailConfirmation_Call struct {
	*mock.Call
}

// EmailConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserService_Expecter) EmailConfirmation(ctx interface{}, userID interface{}) *MockUserService_EmailConfirmation_Call {
	return &MockUserService_EmailConfirmation_Call{Call: _e.mock.On("EmailConfirmation", ctx, userID)}
}

func (_c *MockUserService_EmailConfirmation_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserService_EmailConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_EmailConfirmation_Call) Return(emailConfirmationResponse *dto.EmailConfirmationResponse, err error) *MockUserService_EmailConfirmation_Call {
	_c.Call.Return(emailConfirmationResponse, err)
	return _c
}

func (_c *MockUserService_EmailConfirmation_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*dto.EmailConfirmationResponse, error)) *MockUserService_EmailConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByID(ctx context.Context, userID uuid.UUID) (*dto.UserResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.UserResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.UserResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserService_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockUserService_GetUserByID_Call {
	return &MockUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserService_GetUserByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByID_Call) Return(userResponse *dto.UserResponse, err error) *MockUserService_GetUserByID_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserService_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*dto.UserResponse, error)) *MockUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}
