// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWishlistService creates a new instance of MockWishlistService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWishlistService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWishlistService {
	mock := &MockWishlistService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWishlistService is an autogenerated mock type for the WishlistService type
type MockWishlistService struct {
	mock.Mock
}

type MockWishlistService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWishlistService) EXPECT() *MockWishlistService_Expecter {
	return &MockWishlistService_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) AddItem(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, req dto.AddWishlistItemRequest) (*dto.WishlistResponse, error) {
	ret := _mock.Called(ctx, userID, wishlistID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 *dto.WishlistResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.AddWishlistItemRequest) (*dto.WishlistResponse, error)); ok {
		return returnFunc(ctx, userID, wishlistID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.AddWishlistItemRequest) *dto.WishlistResponse); ok {
		r0 = returnFunc(ctx, userID, wishlistID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WishlistResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.AddWishlistItemRequest) error); ok {
		r1 = returnFunc(ctx, userID, wishlistID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWishlistService_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockWishlistService_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - wishlistID uuid.UUID
//   - req dto.AddWishlistItemRequest
func (_e *MockWishlistService_Expecter) AddItem(ctx interface{}, userID interface{}, wishlistID interface{}, req interface{}) *MockWishlistService_AddItem_Call {
	return &MockWishlistService_AddItem_Call{Call: _e.mock.On("AddItem", ctx, userID, wishlistID, req)}
}

func (_c *MockWishlistService_AddItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, req dto.AddWishlistItemRequest)) *MockWishlistService_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.AddWishlistItemRequest
		if args[3] != nil {
			arg3 = args[3].(dto.AddWishlistItemRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWishlistService_AddItem_Call) Return(wishlistResponse *dto.WishlistResponse, err error) *MockWishlistService_AddItem_Call {
	_c.Call.Return(wishlistResponse, err)
	return _c
}

func (_c *MockWishlistService_AddItem_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, req dto.AddWishlistItemRequest) (*dto.WishlistResponse, error)) *MockWishlistService_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWishlist provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) CreateWishlist(ctx context.Context, userID uuid.UUID, req dto.CreateWishlistRequest) (*dto.WishlistResponse, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateWishlist")
	}

	var r0 *dto.WishlistResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateWishlistRequest) (*dto.WishlistResponse, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateWishlistRequest) *dto.WishlistResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WishlistResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateWishlistRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWishlistService_CreateWishlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWishlist'
type MockWishlistService_CreateWishlist_Call struct {
	*mock.Call
}

// CreateWishlist is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.CreateWishlistRequest
func (_e *MockWishlistService_Expecter) CreateWishlist(ctx interface{}, userID interface{}, req interface{}) *MockWishlistService_CreateWishlist_Call {
	return &MockWishlistService_CreateWishlist_Call{Call: _e.mock.On("CreateWishlist", ctx, userID, req)}
}

func (_c *MockWishlistService_CreateWishlist_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.CreateWishlistRequest)) *MockWishlistService_CreateWishlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.CreateWishlistRequest
		if args[2] != nil {
			arg2 = args[2].(dto.CreateWishlistRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWishlistService_CreateWishlist_Call) Return(wishlistResponse *dto.WishlistResponse, err error) *MockWishlistService_CreateWishlist_Call {
	_c.Call.Return(wishlistResponse, err)
	return _c
}

func (_c *MockWishlistService_CreateWishlist_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.CreateWishlistRequest) (*dto.WishlistResponse, error)) *MockWishlistService_CreateWishlist_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWishlist provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) DeleteWishlist(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, wishlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWishlist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, wishlistID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWishlistService_DeleteWishlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWishlist'
type MockWishlistService_DeleteWishlist_Call struct {
	*mock.Call
}

// DeleteWishlist is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - wishlistID uuid.UUID
func (_e *MockWishlistService_Expecter) DeleteWishlist(ctx interface{}, userID interface{}, wishlistID interface{}) *MockWishlistService_DeleteWishlist_Call {
	return &MockWishlistService_DeleteWishlist_Call{Call: _e.mock.On("DeleteWishlist", ctx, userID, wishlistID)}
}

func (_c *MockWishlistService_DeleteWishlist_Call) Run(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID)) *MockWishlistService_DeleteWishlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWishlistService_DeleteWishlist_Call) Return(err error) *MockWishlistService_DeleteWishlist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWishlistService_DeleteWishlist_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID) error) *MockWishlistService_DeleteWishlist_Call {
	_c.Call.Return(run)
	return _c
}

// GetSharedWishlist provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) GetSharedWishlist(ctx context.Context, shareToken string) (*dto.WishlistResponse, error) {
	ret := _mock.Called(ctx, shareToken)

	if len(ret) == 0 {
		panic("no return value specified for GetSharedWishlist")
	}

	var r0 *dto.WishlistResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.WishlistResponse, error)); ok {
		return returnFunc(ctx, shareToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.WishlistResponse); ok {
		r0 = returnFunc(ctx, shareToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WishlistResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shareToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWishlistService_GetSharedWishlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharedWishlist'
type MockWishlistService_GetSharedWishlist_Call struct {
	*mock.Call
}

// GetSharedWishlist is a helper method to define mock.On call
//   - ctx context.Context
//   - shareToken string
func (_e *MockWishlistService_Expecter) GetSharedWishlist(ctx interface{}, shareToken interface{}) *MockWishlistService_GetSharedWishlist_Call {
	return &MockWishlistService_GetSharedWishlist_Call{Call: _e.mock.On("GetSharedWishlist", ctx, shareToken)}
}

func (_c *MockWishlistService_GetSharedWishlist_Call) Run(run func(ctx context.Context, shareToken string)) *MockWishlistService_GetSharedWishlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWishlistService_GetSharedWishlist_Call) Return(wishlistResponse *dto.WishlistResponse, err error) *MockWishlistService_GetSharedWishlist_Call {
	_c.Call.Return(wishlistResponse, err)
	return _c
}

func (_c *MockWishlistService_GetSharedWishlist_Call) RunAndReturn(run func(ctx context.Context, shareToken string) (*dto.WishlistResponse, error)) *MockWishlistService_GetSharedWishlist_Call {
	_c.Call.Return(run)
	return _c
}

// GetWishlist provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) GetWishlist(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID) (*dto.WishlistResponse, error) {
	ret := _mock.Called(ctx, userID, wishlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetWishlist")
	}

	var r0 *dto.WishlistResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.WishlistResponse, error)); ok {
		return returnFunc(ctx, userID, wishlistID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.WishlistResponse); ok {
		r0 = returnFunc(ctx, userID, wishlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WishlistResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, wishlistID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWishlistService_GetWishlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWishlist'
type MockWishlistService_GetWishlist_Call struct {
	*mock.Call
}

// GetWishlist is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - wishlistID uuid.UUID
func (_e *MockWishlistService_Expecter) GetWishlist(ctx interface{}, userID interface{}, wishlistID interface{}) *MockWishlistService_GetWishlist_Call {
	return &MockWishlistService_GetWishlist_Call{Call: _e.mock.On("GetWishlist", ctx, userID, wishlistID)}
}

func (_c *MockWishlistService_GetWishlist_Call) Run(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID)) *MockWishlistService_GetWishlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWishlistService_GetWishlist_Call) Return(wishlistResponse *dto.WishlistResponse, err error) *MockWishlistService_GetWishlist_Call {
	_c.Call.Return(wishlistResponse, err)
	return _c
}

func (_c *MockWishlistService_GetWishlist_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID) (*dto.WishlistResponse, error)) *MockWishlistService_GetWishlist_Call {
	_c.Call.Return(run)
	return _c
}

// GetWishlists provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) GetWishlists(ctx context.Context, userID uuid.UUID, req dto.ListWishlistRequest) ([]*dto.WishlistResponse, int64, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for GetWishlists")
	}

	var r0 []*dto.WishlistResponse
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ListWishlistRequest) ([]*dto.WishlistResponse, int64, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ListWishlistRequest) []*dto.WishlistResponse); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.WishlistResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.ListWishlistRequest) int64); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, dto.ListWishlistRequest) error); ok {
		r2 = returnFunc(ctx, userID, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWishlistService_GetWishlists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWishlists'
type MockWishlistService_GetWishlists_Call struct {
	*mock.Call
}

// GetWishlists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.ListWishlistRequest
func (_e *MockWishlistService_Expecter) GetWishlists(ctx interface{}, userID interface{}, req interface{}) *MockWishlistService_GetWishlists_Call {
	return &MockWishlistService_GetWishlists_Call{Call: _e.mock.On("GetWishlists", ctx, userID, req)}
}

func (_c *MockWishlistService_GetWishlists_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.ListWishlistRequest)) *MockWishlistService_GetWishlists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.ListWishlistRequest
		if args[2] != nil {
			arg2 = args[2].(dto.ListWishlistRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWishlistService_GetWishlists_Call) Return(wishlistResponses []*dto.WishlistResponse, n int64, err error) *MockWishlistService_GetWishlists_Call {
	_c.Call.Return(wishlistResponses, n, err)
	return _c
}

func (_c *MockWishlistService_GetWishlists_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.ListWishlistRequest) ([]*dto.WishlistResponse, int64, error)) *MockWishlistService_GetWishlists_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateShareToken provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) RegenerateShareToken(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID) (*dto.WishlistShareTokenResponse, error) {
	ret := _mock.Called(ctx, userID, wishlistID)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateShareToken")
	}

	var r0 *dto.WishlistShareTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.WishlistShareTokenResponse, error)); ok {
		return returnFunc(ctx, userID, wishlistID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.WishlistShareTokenResponse); ok {
		r0 = returnFunc(ctx, userID, wishlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WishlistShareTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, wishlistID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWishlistService_RegenerateShareToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateShareToken'
type MockWishlistService_RegenerateShareToken_Call struct {
	*mock.Call
}

// RegenerateShareToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - wishlistID uuid.UUID
func (_e *MockWishlistService_Expecter) RegenerateShareToken(ctx interface{}, userID interface{}, wishlistID interface{}) *MockWishlistService_RegenerateShareToken_Call {
	return &MockWishlistService_RegenerateShareToken_Call{Call: _e.mock.On("RegenerateShareToken", ctx, userID, wishlistID)}
}

func (_c *MockWishlistService_RegenerateShareToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID)) *MockWishlistService_RegenerateShareToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWishlistService_RegenerateShareToken_Call) Return(wishlistShareTokenResponse *dto.WishlistShareTokenResponse, err error) *MockWishlistService_RegenerateShareToken_Call {
	_c.Call.Return(wishlistShareTokenResponse, err)
	return _c
}

func (_c *MockWishlistService_RegenerateShareToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID) (*dto.WishlistShareTokenResponse, error)) *MockWishlistService_RegenerateShareToken_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItem provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) RemoveItem(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, itemID uuid.UUID) (*dto.WishlistResponse, error) {
	ret := _mock.Called(ctx, userID, wishlistID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 *dto.WishlistResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*dto.WishlistResponse, error)); ok {
		return returnFunc(ctx, userID, wishlistID, itemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) *dto.WishlistResponse); ok {
		r0 = returnFunc(ctx, userID, wishlistID, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WishlistResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, wishlistID, itemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWishlistService_RemoveItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItem'
type MockWishlistService_RemoveItem_Call struct {
	*mock.Call
}

// RemoveItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - wishlistID uuid.UUID
//   - itemID uuid.UUID
func (_e *MockWishlistService_Expecter) RemoveItem(ctx interface{}, userID interface{}, wishlistID interface{}, itemID interface{}) *MockWishlistService_RemoveItem_Call {
	return &MockWishlistService_RemoveItem_Call{Call: _e.mock.On("RemoveItem", ctx, userID, wishlistID, itemID)}
}

func (_c *MockWishlistService_RemoveItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, itemID uuid.UUID)) *MockWishlistService_RemoveItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWishlistService_RemoveItem_Call) Return(wishlistResponse *dto.WishlistResponse, err error) *MockWishlistService_RemoveItem_Call {
	_c.Call.Return(wishlistResponse, err)
	return _c
}

func (_c *MockWishlistService_RemoveItem_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, itemID uuid.UUID) (*dto.WishlistResponse, error)) *MockWishlistService_RemoveItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) UpdateItem(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, itemID uuid.UUID, req dto.UpdateWishlistItemRequest) (*dto.WishlistResponse, error) {
	ret := _mock.Called(ctx, userID, wishlistID, itemID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *dto.WishlistResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, dto.UpdateWishlistItemRequest) (*dto.WishlistResponse, error)); ok {
		return returnFunc(ctx, userID, wishlistID, itemID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, dto.UpdateWishlistItemRequest) *dto.WishlistResponse); ok {
		r0 = returnFunc(ctx, userID, wishlistID, itemID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WishlistResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, dto.UpdateWishlistItemRequest) error); ok {
		r1 = returnFunc(ctx, userID, wishlistID, itemID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWishlistService_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockWishlistService_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - wishlistID uuid.UUID
//   - itemID uuid.UUID
//   - req dto.UpdateWishlistItemRequest
func (_e *MockWishlistService_Expecter) UpdateItem(ctx interface{}, userID interface{}, wishlistID interface{}, itemID interface{}, req interface{}) *MockWishlistService_UpdateItem_Call {
	return &MockWishlistService_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, userID, wishlistID, itemID, req)}
}

func (_c *MockWishlistService_UpdateItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, itemID uuid.UUID, req dto.UpdateWishlistItemRequest)) *MockWishlistService_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 dto.UpdateWishlistItemRequest
		if args[4] != nil {
			arg4 = args[4].(dto.UpdateWishlistItemRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWishlistService_UpdateItem_Call) Return(wishlistResponse *dto.WishlistResponse, err error) *MockWishlistService_UpdateItem_Call {
	_c.Call.Return(wishlistResponse, err)
	return _c
}

func (_c *MockWishlistService_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, itemID uuid.UUID, req dto.UpdateWishlistItemRequest) (*dto.WishlistResponse, error)) *MockWishlistService_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWishlist provides a mock function for the type MockWishlistService
func (_mock *MockWishlistService) UpdateWishlist(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, req dto.UpdateWishlistRequest) (*dto.WishlistResponse, error) {
	ret := _mock.Called(ctx, userID, wishlistID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWishlist")
	}

	var r0 *dto.WishlistResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateWishlistRequest) (*dto.WishlistResponse, error)); ok {
		return returnFunc(ctx, userID, wishlistID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateWishlistRequest) *dto.WishlistResponse); ok {
		r0 = returnFunc(ctx, userID, wishlistID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.WishlistResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateWishlistRequest) error); ok {
		r1 = returnFunc(ctx, userID, wishlistID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWishlistService_UpdateWishlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWishlist'
type MockWishlistService_UpdateWishlist_Call struct {
	*mock.Call
}

// UpdateWishlist is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - wishlistID uuid.UUID
//   - req dto.UpdateWishlistRequest
func (_e *MockWishlistService_Expecter) UpdateWishlist(ctx interface{}, userID interface{}, wishlistID interface{}, req interface{}) *MockWishlistService_UpdateWishlist_Call {
	return &MockWishlistService_UpdateWishlist_Call{Call: _e.mock.On("UpdateWishlist", ctx, userID, wishlistID, req)}
}

func (_c *MockWishlistService_UpdateWishlist_Call) Run(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, req dto.UpdateWishlistRequest)) *MockWishlistService_UpdateWishlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.UpdateWishlistRequest
		if args[3] != nil {
			arg3 = args[3].(dto.UpdateWishlistRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWishlistService_UpdateWishlist_Call) Return(wishlistResponse *dto.WishlistResponse, err error) *MockWishlistService_UpdateWishlist_Call {
	_c.Call.Return(wishlistResponse, err)
	return _c
}

func (_c *MockWishlistService_UpdateWishlist_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, wishlistID uuid.UUID, req dto.UpdateWishlistRequest) (*dto.WishlistResponse, error)) *MockWishlistService_UpdateWishlist_Call {
	_c.Call.Return(run)
	return _c
}
