// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"go-shop-backend/pkg/notification"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSenderRegistry creates a new instance of MockSenderRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSenderRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSenderRegistry {
	mock := &MockSenderRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSenderRegistry is an autogenerated mock type for the SenderRegistry type
type MockSenderRegistry struct {
	mock.Mock
}

type MockSenderRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSenderRegistry) EXPECT() *MockSenderRegistry_Expecter {
	return &MockSenderRegistry_Expecter{mock: &_m.Mock}
}

// For provides a mock function for the type MockSenderRegistry
func (_mock *MockSenderRegistry) For(ch notification.Channel) (notification.Sender, bool) {
	ret := _mock.Called(ch)

	if len(ret) == 0 {
		panic("no return value specified for For")
	}

	var r0 notification.Sender
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(notification.Channel) (notification.Sender, bool)); ok {
		return returnFunc(ch)
	}
	if returnFunc, ok := ret.Get(0).(func(notification.Channel) notification.Sender); ok {
		r0 = returnFunc(ch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notification.Sender)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(notification.Channel) bool); ok {
		r1 = returnFunc(ch)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSenderRegistry_For_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'For'
type MockSenderRegistry_For_Call struct {
	*mock.Call
}

// For is a helper method to define mock.On call
//   - ch notification.Channel
func (_e *MockSenderRegistry_Expecter) For(ch interface{}) *MockSenderRegistry_For_Call {
	return &MockSenderRegistry_For_Call{Call: _e.mock.On("For", ch)}
}

func (_c *MockSenderRegistry_For_Call) Run(run func(ch notification.Channel)) *MockSenderRegistry_For_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 notification.Channel
		if args[0] != nil {
			arg0 = args[0].(notification.Channel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSenderRegistry_For_Call) Return(sender notification.Sender, b bool) *MockSenderRegistry_For_Call {
	_c.Call.Return(sender, b)
	return _c
}

func (_c *MockSenderRegistry_For_Call) RunAndReturn(run func(ch notification.Channel) (notification.Sender, bool)) *MockSenderRegistry_For_Call {
	_c.Call.Return(run)
	return _c
}
