// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/pkg/notification"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function for the type MockSender
func (_mock *MockSender) Channel() notification.Channel {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 notification.Channel
	if returnFunc, ok := ret.Get(0).(func() notification.Channel); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(notification.Channel)
	}
	return r0
}

// MockSender_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type MockSender_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
func (_e *MockSender_Expecter) Channel() *MockSender_Channel_Call {
	return &MockSender_Channel_Call{Call: _e.mock.On("Channel")}
}

func (_c *MockSender_Channel_Call) Run(run func()) *MockSender_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSender_Channel_Call) Return(channel notification.Channel) *MockSender_Channel_Call {
	_c.Call.Return(channel)
	return _c
}

func (_c *MockSender_Channel_Call) RunAndReturn(run func() notification.Channel) *MockSender_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockSender
func (_mock *MockSender) Send(ctx context.Context, n notification.Notification) error {
	ret := _mock.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, notification.Notification) error); ok {
		r0 = returnFunc(ctx, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - n notification.Notification
func (_e *MockSender_Expecter) Send(ctx interface{}, n interface{}) *MockSender_Send_Call {
	return &MockSender_Send_Call{Call: _e.mock.On("Send", ctx, n)}
}

func (_c *MockSender_Send_Call) Run(run func(ctx context.Context, n notification.Notification)) *MockSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 notification.Notification
		if args[1] != nil {
			arg1 = args[1].(notification.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSender_Send_Call) Return(err error) *MockSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Send_Call) RunAndReturn(run func(ctx context.Context, n notification.Notification) error) *MockSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
