// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"go-shop-backend/pkg/token"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockManager
func (_mock *MockManager) GenerateAccessToken(payload token.Payload) (string, error) {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(token.Payload) (string, error)); ok {
		return returnFunc(payload)
	}
	if returnFunc, ok := ret.Get(0).(func(token.Payload) string); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(token.Payload) error); ok {
		r1 = returnFunc(payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockManager_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - payload token.Payload
func (_e *MockManager_Expecter) GenerateAccessToken(payload interface{}) *MockManager_GenerateAccessToken_Call {
	return &MockManager_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", payload)}
}

func (_c *MockManager_GenerateAccessToken_Call) Run(run func(payload token.Payload)) *MockManager_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 token.Payload
		if args[0] != nil {
			arg0 = args[0].(token.Payload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_GenerateAccessToken_Call) Return(s string, err error) *MockManager_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockManager_GenerateAccessToken_Call) RunAndReturn(run func(payload token.Payload) (string, error)) *MockManager_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockManager
func (_mock *MockManager) GenerateRefreshToken(payload token.Payload) (string, error) {
	ret := _mock.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(token.Payload) (string, error)); ok {
		return returnFunc(payload)
	}
	if returnFunc, ok := ret.Get(0).(func(token.Payload) string); ok {
		r0 = returnFunc(payload)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(token.Payload) error); ok {
		r1 = returnFunc(payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockManager_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - payload token.Payload
func (_e *MockManager_Expecter) GenerateRefreshToken(payload interface{}) *MockManager_GenerateRefreshToken_Call {
	return &MockManager_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", payload)}
}

func (_c *MockManager_GenerateRefreshToken_Call) Run(run func(payload token.Payload)) *MockManager_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 token.Payload
		if args[0] != nil {
			arg0 = args[0].(token.Payload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_GenerateRefreshToken_Call) Return(s string, err error) *MockManager_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockManager_GenerateRefreshToken_Call) RunAndReturn(run func(payload token.Payload) (string, error)) *MockManager_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockManager
func (_mock *MockManager) ValidateToken(tokenString string) (*token.UserClaims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *token.UserClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*token.UserClaims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *token.UserClaims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.UserClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockManager_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockManager_Expecter) ValidateToken(tokenString interface{}) *MockManager_ValidateToken_Call {
	return &MockManager_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *MockManager_ValidateToken_Call) Run(run func(tokenString string)) *MockManager_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_ValidateToken_Call) Return(userClaims *token.UserClaims, err error) *MockManager_ValidateToken_Call {
	_c.Call.Return(userClaims, err)
	return _c
}

func (_c *MockManager_ValidateToken_Call) RunAndReturn(run func(tokenString string) (*token.UserClaims, error)) *MockManager_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
