// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/pkg/passkey"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// BeginDiscoverableLogin provides a mock function for the type MockManager
func (_mock *MockManager) BeginDiscoverableLogin(ctx context.Context) (*passkey.CredentialAssertion, string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginDiscoverableLogin")
	}

	var r0 *passkey.CredentialAssertion
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*passkey.CredentialAssertion, string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *passkey.CredentialAssertion); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkey.CredentialAssertion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockManager_BeginDiscoverableLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginDiscoverableLogin'
type MockManager_BeginDiscoverableLogin_Call struct {
	*mock.Call
}

// BeginDiscoverableLogin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) BeginDiscoverableLogin(ctx interface{}) *MockManager_BeginDiscoverableLogin_Call {
	return &MockManager_BeginDiscoverableLogin_Call{Call: _e.mock.On("BeginDiscoverableLogin", ctx)}
}

func (_c *MockManager_BeginDiscoverableLogin_Call) Run(run func(ctx context.Context)) *MockManager_BeginDiscoverableLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_BeginDiscoverableLogin_Call) Return(v *passkey.CredentialAssertion, s string, err error) *MockManager_BeginDiscoverableLogin_Call {
	_c.Call.Return(v, s, err)
	return _c
}

func (_c *MockManager_BeginDiscoverableLogin_Call) RunAndReturn(run func(ctx context.Context) (*passkey.CredentialAssertion, string, error)) *MockManager_BeginDiscoverableLogin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginRegistration provides a mock function for the type MockManager
func (_mock *MockManager) BeginRegistration(ctx context.Context, user passkey.User) (*passkey.CredentialCreation, string, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for BeginRegistration")
	}

	var r0 *passkey.CredentialCreation
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, passkey.User) (*passkey.CredentialCreation, string, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, passkey.User) *passkey.CredentialCreation); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkey.CredentialCreation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, passkey.User) string); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, passkey.User) error); ok {
		r2 = returnFunc(ctx, user)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockManager_BeginRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginRegistration'
type MockManager_BeginRegistration_Call struct {
	*mock.Call
}

// BeginRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - user passkey.User
func (_e *MockManager_Expecter) BeginRegistration(ctx interface{}, user interface{}) *MockManager_BeginRegistration_Call {
	return &MockManager_BeginRegistration_Call{Call: _e.mock.On("BeginRegistration", ctx, user)}
}

func (_c *MockManager_BeginRegistration_Call) Run(run func(ctx context.Context, user passkey.User)) *MockManager_BeginRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 passkey.User
		if args[1] != nil {
			arg1 = args[1].(passkey.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_BeginRegistration_Call) Return(v *passkey.CredentialCreation, s string, err error) *MockManager_BeginRegistration_Call {
	_c.Call.Return(v, s, err)
	return _c
}

func (_c *MockManager_BeginRegistration_Call) RunAndReturn(run func(ctx context.Context, user passkey.User) (*passkey.CredentialCreation, string, error)) *MockManager_BeginRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// FinishDiscoverableLogin provides a mock function for the type MockManager
func (_mock *MockManager) FinishDiscoverableLogin(ctx context.Context, handler passkey.DiscoverableUserHandler, sessionID string, data []byte) (passkey.User, *passkey.Credential, error) {
	ret := _mock.Called(ctx, handler, sessionID, data)

	if len(ret) == 0 {
		panic("no return value specified for FinishDiscoverableLogin")
	}

	var r0 passkey.User
	var r1 *passkey.Credential
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, passkey.DiscoverableUserHandler, string, []byte) (passkey.User, *passkey.Credential, error)); ok {
		return returnFunc(ctx, handler, sessionID, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, passkey.DiscoverableUserHandler, string, []byte) passkey.User); ok {
		r0 = returnFunc(ctx, handler, sessionID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(passkey.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, passkey.DiscoverableUserHandler, string, []byte) *passkey.Credential); ok {
		r1 = returnFunc(ctx, handler, sessionID, data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*passkey.Credential)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, passkey.DiscoverableUserHandler, string, []byte) error); ok {
		r2 = returnFunc(ctx, handler, sessionID, data)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockManager_FinishDiscoverableLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishDiscoverableLogin'
type MockManager_FinishDiscoverableLogin_Call struct {
	*mock.Call
}

// FinishDiscoverableLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - handler passkey.DiscoverableUserHandler
//   - sessionID string
//   - data []byte
func (_e *MockManager_Expecter) FinishDiscoverableLogin(ctx interface{}, handler interface{}, sessionID interface{}, data interface{}) *MockManager_FinishDiscoverableLogin_Call {
	return &MockManager_FinishDiscoverableLogin_Call{Call: _e.mock.On("FinishDiscoverableLogin", ctx, handler, sessionID, data)}
}

func (_c *MockManager_FinishDiscoverableLogin_Call) Run(run func(ctx context.Context, handler passkey.DiscoverableUserHandler, sessionID string, data []byte)) *MockManager_FinishDiscoverableLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 passkey.DiscoverableUserHandler
		if args[1] != nil {
			arg1 = args[1].(passkey.DiscoverableUserHandler)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockManager_FinishDiscoverableLogin_Call) Return(v passkey.User, v1 *passkey.Credential, err error) *MockManager_FinishDiscoverableLogin_Call {
	_c.Call.Return(v, v1, err)
	return _c
}

func (_c *MockManager_FinishDiscoverableLogin_Call) RunAndReturn(run func(ctx context.Context, handler passkey.DiscoverableUserHandler, sessionID string, data []byte) (passkey.User, *passkey.Credential, error)) *MockManager_FinishDiscoverableLogin_Call {
	_c.Call.Return(run)
	return _c
}

// FinishRegistration provides a mock function for the type MockManager
func (_mock *MockManager) FinishRegistration(ctx context.Context, user passkey.User, sessionID string, data []byte) (*passkey.Credential, error) {
	ret := _mock.Called(ctx, user, sessionID, data)

	if len(ret) == 0 {
		panic("no return value specified for FinishRegistration")
	}

	var r0 *passkey.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, passkey.User, string, []byte) (*passkey.Credential, error)); ok {
		return returnFunc(ctx, user, sessionID, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, passkey.User, string, []byte) *passkey.Credential); ok {
		r0 = returnFunc(ctx, user, sessionID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkey.Credential)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, passkey.User, string, []byte) error); ok {
		r1 = returnFunc(ctx, user, sessionID, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_FinishRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishRegistration'
type MockManager_FinishRegistration_Call struct {
	*mock.Call
}

// FinishRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - user passkey.User
//   - sessionID string
//   - data []byte
func (_e *MockManager_Expecter) FinishRegistration(ctx interface{}, user interface{}, sessionID interface{}, data interface{}) *MockManager_FinishRegistration_Call {
	return &MockManager_FinishRegistration_Call{Call: _e.mock.On("FinishRegistration", ctx, user, sessionID, data)}
}

func (_c *MockManager_FinishRegistration_Call) Run(run func(ctx context.Context, user passkey.User, sessionID string, data []byte)) *MockManager_FinishRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 passkey.User
		if args[1] != nil {
			arg1 = args[1].(passkey.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockManager_FinishRegistration_Call) Return(v *passkey.Credential, err error) *MockManager_FinishRegistration_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockManager_FinishRegistration_Call) RunAndReturn(run func(ctx context.Context, user passkey.User, sessionID string, data []byte) (*passkey.Credential, error)) *MockManager_FinishRegistration_Call {
	_c.Call.Return(run)
	return _c
}
