// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-shop-backend/pkg/passkey"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// DeleteSession provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) DeleteSession(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStore_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionStore_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionStore_Expecter) DeleteSession(ctx interface{}, sessionID interface{}) *MockSessionStore_DeleteSession_Call {
	return &MockSessionStore_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID)}
}

func (_c *MockSessionStore_DeleteSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionStore_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStore_DeleteSession_Call) Return(err error) *MockSessionStore_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStore_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockSessionStore_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) GetSession(ctx context.Context, sessionID string) (*passkey.SessionData, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *passkey.SessionData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*passkey.SessionData, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *passkey.SessionData); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkey.SessionData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionStore_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionStore_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionStore_Expecter) GetSession(ctx interface{}, sessionID interface{}) *MockSessionStore_GetSession_Call {
	return &MockSessionStore_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID)}
}

func (_c *MockSessionStore_GetSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionStore_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStore_GetSession_Call) Return(v *passkey.SessionData, err error) *MockSessionStore_GetSession_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockSessionStore_GetSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*passkey.SessionData, error)) *MockSessionStore_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) SaveSession(ctx context.Context, sessionID string, data *passkey.SessionData) error {
	ret := _mock.Called(ctx, sessionID, data)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *passkey.SessionData) error); ok {
		r0 = returnFunc(ctx, sessionID, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStore_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type MockSessionStore_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - data *passkey.SessionData
func (_e *MockSessionStore_Expecter) SaveSession(ctx interface{}, sessionID interface{}, data interface{}) *MockSessionStore_SaveSession_Call {
	return &MockSessionStore_SaveSession_Call{Call: _e.mock.On("SaveSession", ctx, sessionID, data)}
}

func (_c *MockSessionStore_SaveSession_Call) Run(run func(ctx context.Context, sessionID string, data *passkey.SessionData)) *MockSessionStore_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *passkey.SessionData
		if args[2] != nil {
			arg2 = args[2].(*passkey.SessionData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStore_SaveSession_Call) Return(err error) *MockSessionStore_SaveSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStore_SaveSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string, data *passkey.SessionData) error) *MockSessionStore_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}
